Repository multitheftauto/mtasa-blue, pull requests merged in 2018-07, with the labels that each got.

#195 Extending the ColShape class with point checking functionality
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
Labels: enhancement

#208 Feature for mapping. setWorldSpecialPropertyEnabled, `underworldwarp` property
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CWorldSA.cpp
  Client/game_sa/CWorldSA.h
Labels: enhancement, pr:tested

#216 #9033 - Fix setVehicleColor (Client) right after creating vehicle
  Client/mods/deathmatch/logic/CClientVehicle.cpp
Labels: bugfix

#229 0009522: reset jetpack and choking states upon animation - and the other way around
  Client/mods/deathmatch/logic/CClientPed.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bugfix, pr:needs-testing

#244 Fix #9914 [BUG] Having a variable called 'type' brokes exports.lua
  Shared/mods/deathmatch/logic/luascripts/exports.lua.h
Labels: bugfix

#228 0009896: add a master volume level setting
  Client/core/CClientVariables.cpp
  Client/core/CCore.cpp
  Client/core/CSettings.cpp
  Client/core/CSettings.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientPlayerVoice.cpp
  Client/mods/deathmatch/logic/CClientSoundManager.cpp
Labels: enhancement

#225 0009898: add setVehicleModelExhaustFumesPosition and getVehicleModelExhaustFumesPosition OOP methods
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
Labels: enhancement

#231 function: get/set/resetPedsLODDistance
  Client/game_sa/CSettingsSA.cpp
  Client/game_sa/CSettingsSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.World.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.h
  Client/mods/deathmatch/logic/lua/CLuaManager.cpp
  Client/sdk/game/CSettings.h
Labels: new feature, pr:needs-testing, waiting for feedback

#243 Function setPedWearingJetpack
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/rpc/CPedRPCs.h
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/lua/CLuaManager.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
Labels: enhancement
