Repository multitheftauto/mtasa-blue, pull requests merged in 2018-02, with the labels that each got.

#125 setCameraViewMode for trains
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: enhancement

#131 Added reloadacl command for server console (#9626)
  Server/mods/deathmatch/acl.xml
  Server/mods/deathmatch/logic/CConsoleCommands.cpp
  Server/mods/deathmatch/logic/CConsoleCommands.h
  Server/mods/deathmatch/logic/CMainConfig.cpp
Labels: enhancement, pr:needs-testing

#146 Function: isVehicleWheelCollided
  Client/game_sa/CDamageManagerSA.cpp
  Client/game_sa/CDamageManagerSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/CClientWeapon.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Client/sdk/game/CDamageManager.h
  Client/sdk/game/CVehicle.h
  Server/mods/deathmatch/logic/CVehicle.h
Labels: enhancement, pr:needs-testing

#148 [1.6] Fix animation being stuck after carjack sometimes
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: bugfix

#126 Add pre/postEventFunction to addDebugHook
  Client/mods/deathmatch/logic/CMapEventManager.cpp
  Server/mods/deathmatch/logic/CMapEventManager.cpp
  Shared/mods/deathmatch/logic/CDebugHookManager.cpp
  Shared/mods/deathmatch/logic/CDebugHookManager.h
  Shared/mods/deathmatch/logic/Enums.cpp
  Shared/mods/deathmatch/logic/Enums.h
Labels: enhancement, pr:needs-testing

#149 IsPedReloadingWeapon - new function (mantis 9664)
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CClientPed.h
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
Labels: enhancement

#155 CModelInfoSA exceeds an array boundaries
  Client/game_sa/CModelInfoSA.cpp
Labels: bugfix, pr:needs-testing
