Repository multitheftauto/mtasa-blue, pull requests merged in 2018-09, with the labels that each got.

#363 Fix compiler warning about signed/unsigned mismatch in CPrimitiveMaterialBatcher
  Client/core/Graphics/CPrimitiveMaterialBatcher.cpp
Labels: bug

#379 Fix swimming speed on higher FPS
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: bug

#378 Fix for issue #377 (many collisionless objects)
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
Labels: bug

#338 Add setVehicleRespawnRotation function and tweaked OOP variants
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
Labels: enhancement

#316 Enable safe Lua os.* functions
  Client/mods/deathmatch/logic/lua/CLuaMain.cpp
  Server/mods/deathmatch/logic/lua/CLuaMain.cpp
Labels: enhancement

#401 Fix for issue #397 (the same vehicle handling)
  Client/game_sa/CHandlingManagerSA.cpp
  Client/sdk/game/Common.h
  Server/mods/deathmatch/logic/CCommon.h
  Server/mods/deathmatch/logic/CHandlingManager.cpp
Labels: bug

#420 Add new function getCurrentFPS
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.World.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.h
  Client/mods/deathmatch/logic/lua/CLuaManager.cpp
Labels: enhancement

#360 Moved function into proper sections
  Client/mods/deathmatch/logic/lua/CLuaManager.cpp
Labels: enhancement, refactor

#441 Add option to create shader from raw data
  Client/core/DXHook/CProxyDirect3DEffect.cpp
  Client/core/DXHook/CProxyDirect3DEffect.h
  Client/core/Graphics/CRenderItem.EffectCloner.cpp
  Client/core/Graphics/CRenderItem.EffectCloner.h
  Client/core/Graphics/CRenderItem.EffectTemplate.cpp
  Client/core/Graphics/CRenderItem.EffectTemplate.h
  Client/core/Graphics/CRenderItem.Shader.cpp
  Client/core/Graphics/CRenderItemManager.cpp
  Client/core/Graphics/CRenderItemManager.h
  Client/mods/deathmatch/logic/CClientRenderElementManager.cpp
  Client/mods/deathmatch/logic/CClientRenderElementManager.h
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Client/sdk/core/CRenderItemManagerInterface.h
Labels: enhancement

#390 Add possiblity to change vehicle model dummies positions
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Client/sdk/game/CModelInfo.h
  Client/sdk/game/Common.h
Labels: enhancement

#433 Skimmer high fps fix
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: bug

#391 Ability to pass vectors and matrices to shaders
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Shared/sdk/CMatrix.h
Labels: enhancement

#280 Add gui combobox missing functions
  Client/gui/CGUIComboBox_Impl.cpp
  Client/gui/CGUIComboBox_Impl.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.h
  Client/sdk/gui/CGUIComboBox.h
Labels: enhancement

#361 Add possibility to modify vehicle components scale
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Client/sdk/game/CVehicle.h
  Shared/sdk/CMatrix.h
  Shared/sdk/CVector.h
Labels: enhancement

#477 Feature: event onClientWaterCannonHit
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/sdk/multiplayer/CMultiplayer.h
Labels: enhancement
