Repository multitheftauto/mtasa-blue, pull requests merged in 2018-08, with the labels that each got.

#279 #278: fix blip code inconsistencies and clamp size value for backwards compatibility
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaBlipDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaBlipDefs.cpp
Labels: bug

#266 Feature: function dxDrawCircle
  Client/core/Graphics/CGraphics.cpp
  Client/core/Graphics/CGraphics.h
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.h
  Client/sdk/core/CGraphicsInterface.h
Labels: enhancement, new feature

#302 Move tocolor and gettok to shared function definitions
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Util.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.h
  Client/mods/deathmatch/logic/lua/CLuaManager.cpp
  Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.Utility.cpp
  Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.h
  Server/mods/deathmatch/logic/lua/CLuaManager.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaUtilDefs.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaUtilDefs.h
Labels: enhancement, refactor

#258 0008540: fix spawnPlayer rotation not setting if an object is near the spawn point
  Client/mods/deathmatch/logic/CClientPed.cpp
Labels: bug, pr:needs-testing

#312 Improve debug info for garbage collected files
  Client/mods/deathmatch/logic/CScriptFile.h
  Server/mods/deathmatch/logic/CScriptFile.h
  Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp
Labels: enhancement

#308 #304: Fixed inconsistencies in Player 'get' functions
  Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
Labels: bug

#305 Fix getElementBoundingBox() OOP version returning 6 numbers instead of a 2 vectors
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
Labels: bug

#332 Backward compatibility fix for OOP_GetElementBoundingBox returning vectors post-r13998
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
Labels: bug

#335 Updated libpng from 1.6.23 to 1.6.35
  vendor/libpng/png.c
  vendor/libpng/png.h
  vendor/libpng/pngconf.h
  vendor/libpng/pngerror.c
  vendor/libpng/pngget.c
  vendor/libpng/pnginfo.h
  vendor/libpng/pngmem.c
  vendor/libpng/pngpread.c
  vendor/libpng/pngpriv.h
  vendor/libpng/pngread.c
  vendor/libpng/pngrio.c
  vendor/libpng/pngrtran.c
  vendor/libpng/pngrutil.c
  vendor/libpng/pngset.c
  vendor/libpng/pngstruct.h
  vendor/libpng/pngtest.c
  vendor/libpng/pngtrans.c
  vendor/libpng/pngwio.c
  vendor/libpng/pngwrite.c
  vendor/libpng/pngwtran.c
  vendor/libpng/pngwutil.c
Labels: enhancement

#151 Added dynamic ped ID allocating(based on lopezloo pull request)
  Client/core/CModelCacheManager.h
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/StdInc.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientManager.cpp
  Client/mods/deathmatch/logic/CClientManager.h
  Client/mods/deathmatch/logic/CClientModel.cpp
  Client/mods/deathmatch/logic/CClientModel.h
  Client/mods/deathmatch/logic/CClientModelManager.cpp
  Client/mods/deathmatch/logic/CClientModelManager.h
  Client/mods/deathmatch/logic/CClientPlayerManager.cpp
  Client/mods/deathmatch/logic/CResource.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
  Client/sdk/game/CGame.h
  Client/sdk/game/CModelInfo.h
Labels: new feature, question, refactor

#342 Fix CAnimBlendNode crashes when leaving server
  Client/game_sa/CAnimBlendAssociationSA.cpp
  Client/game_sa/CAnimBlendAssociationSA.h
  Client/game_sa/CAnimManagerSA.cpp
  Client/game_sa/CAnimManagerSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/multiplayer_sa/CMultiplayerSA_CustomAnimations.cpp
  Client/sdk/game/CAnimBlendAssociation.h
  Client/sdk/game/CAnimManager.h
  Client/sdk/multiplayer/CMultiplayer.h
Labels: bug

#254 0009611: refactor GUIGetChatboxLayout, and add the CVar argument as advertised on Wiki
  Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.h
Labels: refactor

#215 Function: clearChat
  Client/core/CCore.cpp
  Client/core/CCore.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CPacketHandler.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Output.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.h
  Client/mods/deathmatch/logic/lua/CLuaManager.cpp
  Client/sdk/core/CCoreInterface.h
  Server/mods/deathmatch/StdInc.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.Server.cpp
  Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.h
  Server/mods/deathmatch/logic/lua/CLuaManager.cpp
  Server/mods/deathmatch/logic/packets/CChatClearPacket.cpp
  Server/mods/deathmatch/logic/packets/CChatClearPacket.h
  Shared/sdk/net/Packets.h
Labels: new feature

#73 Added get/setElementAngularVelocity
  Client/game_sa/CPhysicalSA.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
  Client/mods/deathmatch/logic/rpc/CElementRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CElementRPCs.h
  Server/mods/deathmatch/logic/CPerfStat.RPCPacketUsage.cpp
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
  Shared/sdk/net/rpc_enums.h
Labels: new feature

#274 0009814: add server console arrow command history
  Server/core/CServerImpl.cpp
  Server/core/CServerImpl.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/sdk/core/CServerInterface.h
Labels: enhancement

#355 Re-fit mute options in the audio tab
  Client/core/CSettings.cpp
Labels: bug

#339 Queued dxDrawPrimitive and dxDrawMaterialPrimitive
  Client/core/Graphics/CGraphics.cpp
  Client/core/Graphics/CGraphics.h
  Client/core/Graphics/CPrimitiveBatcher.cpp
  Client/core/Graphics/CPrimitiveBatcher.h
  Client/core/Graphics/CPrimitiveMaterialBatcher.cpp
  Client/core/Graphics/CPrimitiveMaterialBatcher.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.h
  Client/sdk/core/CGraphicsInterface.h
  Shared/sdk/CScriptArgReader.h
Labels: enhancement
