Repository multitheftauto/mtasa-blue, pull requests merged in 2020-11, with the labels that each got.

#1684 Allow allocating new object models using engineRequestModel
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/game_sa/CRenderWareSA.TextureReplacing.cpp
  Client/game_sa/CStreamingSA.cpp
  Client/game_sa/CStreamingSA.h
  Client/mods/deathmatch/logic/CClientModel.cpp
  Client/mods/deathmatch/logic/CClientModel.h
  Client/mods/deathmatch/logic/CClientObjectManager.cpp
  Client/mods/deathmatch/logic/CClientObjectManager.h
  Client/mods/deathmatch/logic/CResource.cpp
  Client/mods/deathmatch/logic/CResourceManager.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Util.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/multiplayer_sa/CMultiplayerSA_CrashFixHacks.cpp
  Client/sdk/game/CModelInfo.h
  Client/sdk/game/CStreaming.h
  Shared/sdk/SharedUtil.Misc.h
Labels: enhancement

#1402 setWaterLevel: add bIncludeWorldSeaLevel and bIncludeOutsideWorldLevel
  Client/game_sa/CWaterManagerSA.cpp
  Client/game_sa/CWaterManagerSA.h
  Client/mods/deathmatch/logic/CClientWaterManager.cpp
  Client/mods/deathmatch/logic/CClientWaterManager.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaWaterDefs.cpp
  Client/mods/deathmatch/logic/rpc/CWaterRPCs.cpp
  Client/sdk/game/CWaterManager.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/CWaterManager.cpp
  Server/mods/deathmatch/logic/CWaterManager.h
  Server/mods/deathmatch/logic/luadefs/CLuaWaterDefs.cpp
  Server/mods/deathmatch/logic/packets/CMapInfoPacket.cpp
  Server/mods/deathmatch/logic/packets/CMapInfoPacket.h
  Shared/sdk/net/bitstream.h
Labels: enhancement

#1788 Refactor CPlayerStatsPacket
  Server/mods/deathmatch/logic/packets/CPlayerStatsPacket.cpp
  Server/mods/deathmatch/logic/packets/CPlayerStatsPacket.h
Labels: refactor

#1778 Improve checksum error messages for internal HTTP servers
  Client/mods/deathmatch/logic/CDownloadableResource.cpp
  Client/mods/deathmatch/logic/CResource.cpp
  Client/mods/deathmatch/logic/CResourceFileDownloadManager.cpp
  Client/mods/deathmatch/logic/CResourceManager.cpp
  Client/mods/deathmatch/logic/CSingularFileDownload.cpp
  Server/mods/deathmatch/logic/CResource.cpp
  Shared/sdk/CChecksum.h
Labels: bug

#1808 Fix access violation in CHandlingManagerSA
  Client/game_sa/CHandlingManagerSA.cpp
Labels: bug

#1611 Function to override the color filtering values
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.h
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/sdk/multiplayer/CMultiplayer.h
Labels: enhancement

#1812 Fix #1810: Random crashes in latest nightly
  Client/game_sa/CBikeSA.cpp
  Client/game_sa/CBikeSA.h
  Client/game_sa/CBoatSA.cpp
  Client/game_sa/CBoatSA.h
  Client/game_sa/CFlyingHandlingEntrySA.cpp
  Client/game_sa/CVehicleSA.cpp
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
Labels: bug

#1818 Fix #927: "Random collisionless objects" still exist
  Client/game_sa/CModelInfoSA.cpp
Labels: bug

#1553 Fix #1539: Add on(Client)ElementDimensionChange event
  Client/mods/deathmatch/logic/CClientEntity.cpp
  Client/mods/deathmatch/logic/CClientEntity.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientPointLights.cpp
  Client/mods/deathmatch/logic/CClientRadarArea.cpp
  Client/mods/deathmatch/logic/CClientRadarArea.h
  Client/mods/deathmatch/logic/CClientRadarMarker.cpp
  Client/mods/deathmatch/logic/CClientRadarMarker.h
  Client/mods/deathmatch/logic/CClientStreamElement.cpp
  Client/mods/deathmatch/logic/CClientStreamElement.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CElement.cpp
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CGame.cpp
Labels: enhancement

#1768 Remove unused Lua manager pointer from some classes
  Server/mods/deathmatch/logic/CConsole.cpp
  Server/mods/deathmatch/logic/CConsole.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CMainConfig.cpp
  Server/mods/deathmatch/logic/CMainConfig.h
  Server/mods/deathmatch/logic/CMapManager.cpp
  Server/mods/deathmatch/logic/CMapManager.h
  Server/mods/deathmatch/logic/CScriptDebugging.cpp
  Server/mods/deathmatch/logic/CScriptDebugging.h
Labels: bug

#1839 Add getVehicleWheelFrictionState function
  Client/game_sa/CAutomobileSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Client/sdk/game/CVehicle.h
Labels: enhancement

#1844 Fix #1819: Crash on reconnect 1.5.8-release-20704.0.000
  Client/mods/deathmatch/logic/CClientModelManager.cpp
Labels: bug

#1847 Revert "Fix #927: "Random collisionless objects" still exist (#1818)"
  Client/game_sa/CModelInfoSA.cpp
Labels: bug

#1846 Fix #1840: engineRequestModel crash on disconnect
  Client/mods/deathmatch/logic/CClientManager.cpp
  Client/mods/deathmatch/logic/CClientModel.cpp
  Client/mods/deathmatch/logic/CClientModel.h
  Client/mods/deathmatch/logic/CClientModelManager.cpp
  Client/mods/deathmatch/logic/CClientModelManager.h
  Client/mods/deathmatch/logic/CClientObject.cpp
  Client/mods/deathmatch/logic/CClientObject.h
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CClientPed.h
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Util.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
Labels: bug

#1848 Make `logIn` password argument optional
  Server/mods/deathmatch/logic/CAccountManager.cpp
  Server/mods/deathmatch/logic/CAccountManager.h
  Server/mods/deathmatch/logic/luadefs/CLuaAccountDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaAccountDefs.h
Labels: enhancement

#1866 Fix some model crashes
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientModelManager.cpp
  Client/mods/deathmatch/logic/CClientObjectManager.cpp
  Client/sdk/game/CModelInfo.h
Labels: bug

#1870 Make 3118 and 3553 usable
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
Labels: bug

#1868 Fix crash for crane
  Client/game_sa/CObjectSA.cpp
  Client/game_sa/CRopesSA.cpp
  Client/game_sa/CRopesSA.h
  Client/sdk/game/CRopes.h
Labels: bug

#1806 Return Lua table matrix in getElementBoneMatrix #1805
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
  Shared/mods/deathmatch/logic/lua/LuaBasic.h
  Shared/sdk/CMatrix.h
Labels: bug

#1855 Refactor LogIn function
  Server/mods/deathmatch/logic/CAccountManager.cpp
  Server/mods/deathmatch/logic/CAccountManager.h
  Server/mods/deathmatch/logic/CConsoleCommands.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaAccountDefs.cpp
Labels: refactor

#1748 Implement entering/exiting/jacking for peds
  Client/mods/deathmatch/ClientCommands.cpp
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CClientPed.h
  Client/mods/deathmatch/logic/CNetAPI.cpp
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CPedSync.cpp
  Client/mods/deathmatch/logic/CPedSync.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CMapManager.cpp
  Server/mods/deathmatch/logic/CPed.cpp
  Server/mods/deathmatch/logic/CPed.h
  Server/mods/deathmatch/logic/CPlayer.cpp
  Server/mods/deathmatch/logic/CPlayer.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CVehicle.cpp
  Server/mods/deathmatch/logic/CVehicle.h
  Server/mods/deathmatch/logic/packets/CVehicleInOutPacket.cpp
  Server/mods/deathmatch/logic/packets/CVehicleInOutPacket.h
  Shared/sdk/net/bitstream.h
Labels: enhancement, hacktoberfest-accepted
