Repository multitheftauto/mtasa-blue, pull requests merged in 2020-07, with the labels that each got.

#1569 Improve patcher logging
  Client/loader/CFileGenerator.cpp
  Client/loader/CInstallManager.cpp
Labels: enhancement

#1575 Fix detection of some dff's
  Client/mods/deathmatch/logic/CClientDFF.cpp
Labels: bug

#1531 Fix xmlLoadString memory leak
  Client/mods/deathmatch/logic/lua/CLuaMain.cpp
  Client/mods/deathmatch/logic/lua/CLuaMain.h
  Server/mods/deathmatch/logic/lua/CLuaMain.cpp
  Server/mods/deathmatch/logic/lua/CLuaMain.h
Labels: bug

#1481 Refactor newly added drawing functions to use the new parser
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.h
  Shared/mods/deathmatch/logic/lua/LuaBasic.h
Labels: refactor

#1584 Fix broken dxGetTextWidth caused by 625e86b23eaf
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
Labels: bug
