Repository multitheftauto/mtasa-blue, pull requests merged in 2020-12, with the labels that each got.

#1889 Fix incorrect indexing introduced in export refactor
  Client/mods/deathmatch/logic/luadefs/CLuaResourceDefs.cpp
Labels: bug

#1859 FLA compatibility - possible different file ID and world map sector limits
  Client/core/CMemStats.cpp
  Client/game_sa/CAnimBlockSA.cpp
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/game_sa/CObjectGroupPhysicalPropertiesSA.cpp
  Client/game_sa/CObjectSA.cpp
  Client/game_sa/CPoolsSA.cpp
  Client/game_sa/CRenderWareSA.ClothesReplacing.cpp
  Client/game_sa/CRenderWareSA.ShaderSupport.cpp
  Client/game_sa/CRenderWareSA.cpp
  Client/game_sa/CStreamingSA.cpp
  Client/game_sa/CStreamingSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientModelManager.cpp
  Client/mods/deathmatch/logic/CClientModelManager.h
  Client/mods/deathmatch/logic/CClientObjectManager.cpp
  Client/mods/deathmatch/logic/CClientPlayerManager.cpp
  Client/mods/deathmatch/logic/CModelNames.cpp
  Client/mods/deathmatch/logic/CModelNames.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA_ClothesSpeedUp.cpp
  Client/multiplayer_sa/CMultiplayerSA_CrashFixHacks.cpp
  Client/multiplayer_sa/CMultiplayerSA_ObjectLODSystem.cpp
  Client/multiplayer_sa/CMultiplayerSA_Streaming.cpp
  Client/sdk/game/CGame.h
  Client/sdk/game/CStreaming.h
Labels: enhancement

#1897 Fix IFP crash caused by fe9d419e2564926976490b5e26d4ca6cf8d4ed79
  Client/game_sa/CGameSA.h
Labels: bug

#1902 Move backwards compatibility functions to CLuaCompatibilityDefs
  Client/mods/deathmatch/StdInc.h
  Client/mods/deathmatch/logic/lua/CLuaManager.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaCompatibilityDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaCompatibilityDefs.h
  Server/mods/deathmatch/StdInc.h
  Server/mods/deathmatch/logic/lua/CLuaManager.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaCompatibilityDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaCompatibilityDefs.h
Labels: refactor

#1904 Fix incorrect address for CStreaming::ms_aInfoForModel
  Client/core/CMemStats.cpp
Labels: bug

#1907 Fix #908: vehicle driver desync after carjacker dies
  Client/mods/deathmatch/logic/CClientPed.cpp
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#1798 Add final where possible - server
  Server/mods/deathmatch/logic/CConsoleClient.h
  Server/mods/deathmatch/logic/CDummy.h
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CPickup.h
  Server/mods/deathmatch/logic/CPlayer.h
  Server/mods/deathmatch/logic/CScriptFile.h
  Server/mods/deathmatch/logic/CTeam.h
  Server/mods/deathmatch/logic/CTrainTrack.h
  Server/mods/deathmatch/logic/CVehicle.h
  Server/mods/deathmatch/logic/CWater.h
Labels: refactor

#1852 add override argument to setAnalogControlState
  Client/mods/deathmatch/logic/CClientPad.cpp
  Client/mods/deathmatch/logic/CClientPad.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Input.cpp
Labels: bug, enhancement

#1890 Fix #1836: setObjectScale onClientPedsProcessed event
  Client/game_sa/CEntitySA.cpp
  Client/game_sa/CEntitySA.h
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CObjectSA.cpp
  Client/game_sa/CObjectSA.h
  Client/game_sa/CPoolsSA.cpp
  Client/game_sa/CPoolsSA.h
  Client/game_sa/gamesa_renderware.h
  Client/game_sa/gamesa_renderware.hpp
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA_1.3.cpp
  Client/sdk/game/CEntity.h
  Client/sdk/game/CObject.h
  Client/sdk/game/CPools.h
  Client/sdk/game/RenderWare.h
Labels: bug

#1912 Add smart pointer overloads to lua::Push
  Shared/mods/deathmatch/logic/lua/LuaBasic.h
Labels: enhancement

#1923 Fix typo in Sound.setPanningEnabled OOP-method name
  Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.cpp
Labels: bug

#1930 Re-introduce "Random collisionless objects" fix
  Client/game_sa/CModelInfoSA.cpp
Labels: bug

#1933 Fix crash related to texture loading
  Client/game_sa/CModelInfoSA.cpp
Labels: bug

#1943 Fix #1942: Ped task bug when fighting near to a vehicle
  Client/mods/deathmatch/logic/CClientGame.cpp
Labels: bug

#1914 Fix a few new parser issues
  Shared/mods/deathmatch/logic/lua/LuaBasic.h
Labels: bug

#70 0004824: Fix incorrect Bloodring Banger enter/exit animation
  Client/mods/deathmatch/logic/CClientVehicleManager.cpp
  Server/mods/deathmatch/logic/CVehicleManager.cpp
Labels: backwards-incompatible, bug

#1958 Fix disappearance of the collision of the world (#1948)
  Client/game_sa/CModelInfoSA.cpp
Labels: bug

#1951 Fixup ecabcfbb6ca (#1914)
  Shared/mods/deathmatch/logic/lua/LuaBasic.h
Labels: bug

#1966 Revert login behavior changes
  Server/mods/deathmatch/logic/CAccountManager.cpp
  Server/mods/deathmatch/logic/CAccountManager.h
  Server/mods/deathmatch/logic/CConsoleCommands.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaAccountDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaAccountDefs.h
Labels: bug
