Repository multitheftauto/mtasa-blue, pull requests merged in 2020-06, with the labels that each got.

#1483 Refactor newly added veh functions to use the new parser
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
Labels: refactor

#1484 Refactor newly added ped functions to use the new parser
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
Labels: refactor

#1501 Remove amx from installer
  Shared/installer/nightly.nsi
Labels: bug

#1498 Downgrade CEF to 81.3.10+gb223419+chromium-81.0.4044.138
  utils/buildactions/install_cef.lua
Labels: bug

#1485 Fix getModuleInfo
  Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.Server.cpp
Labels: bug

#1477 Fix off-by-one in off-by-one in error messages fix (31e90bb)
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
Labels: bug

#1524 Potential fix for vehicle dummies crash
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
Labels: bug

#1528 Revert "Multi-thread DB Queue (#1242)"
  Server/mods/deathmatch/logic/CDatabaseJobQueue.cpp
  Server/mods/deathmatch/logic/CDatabaseJobQueue.h
  Server/mods/deathmatch/logic/CDatabaseJobQueueManager.cpp
  Server/mods/deathmatch/logic/CDatabaseJobQueueManager.h
  Server/mods/deathmatch/logic/CDatabaseManager.cpp
  Server/mods/deathmatch/logic/CDatabaseManager.h
  Server/mods/deathmatch/logic/luadefs/CLuaDatabaseDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaDatabaseDefs.h
Labels: bug

#1530 Allow hourOn to be greater than hourOff for engineSetModelVisibleTime
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
Labels: bug

#1538 Badges for README.md
  README.md
Labels: documentation

#1534 Fix #1443 - trim teaEncode trailing zeroes
  Shared/sdk/SharedUtil.Hash.h
  Shared/sdk/SharedUtil.Hash.hpp
Labels: bug

#1550 Add projectiles support for getElementModel
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug
