Repository multitheftauto/mtasa-blue, pull requests merged in 2020-04, with the labels that each got.

#1167 Fix #1158: add outputDebugString level 4 to omit debug info
  Client/mods/deathmatch/logic/CScriptDebugging.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Output.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Util.cpp
  Server/mods/deathmatch/logic/CScriptDebugging.h
  Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.Server.cpp
  Shared/mods/deathmatch/logic/CScriptDebugging.cpp
Labels: enhancement

#752 Add engineSet/GetModelTime
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
  Client/sdk/game/CGame.h
  Client/sdk/game/CModelInfo.h
  Client/sdk/game/RenderWare.h
Labels: enhancement

#1055 Add element data subscription
  Server/mods/deathmatch/logic/CCustomData.cpp
  Server/mods/deathmatch/logic/CCustomData.h
  Server/mods/deathmatch/logic/CElement.cpp
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CElementDeleter.cpp
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CPlayer.cpp
  Server/mods/deathmatch/logic/CPlayer.h
  Server/mods/deathmatch/logic/CPlayerManager.cpp
  Server/mods/deathmatch/logic/CPlayerManager.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
  Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp
Labels: enhancement

#263 0009891: Add support for more map attributes
  Server/mods/deathmatch/logic/CBlip.cpp
  Server/mods/deathmatch/logic/CObject.cpp
  Server/mods/deathmatch/logic/CPed.cpp
  Server/mods/deathmatch/logic/CTeam.cpp
  Server/mods/deathmatch/logic/CVehicle.cpp
Labels: enhancement

#1261 Fix #1258: Add mixed hex and RGB(A) parsing to XMLColorToInt
  Server/mods/deathmatch/logic/CVehicle.cpp
  Server/mods/deathmatch/logic/Utils.cpp
  Server/mods/deathmatch/logic/Utils.h
Labels: enhancement

#1242 Multi-thread DB Queue
  Server/mods/deathmatch/logic/CDatabaseJobQueue.cpp
  Server/mods/deathmatch/logic/CDatabaseJobQueue.h
  Server/mods/deathmatch/logic/CDatabaseJobQueueManager.cpp
  Server/mods/deathmatch/logic/CDatabaseJobQueueManager.h
  Server/mods/deathmatch/logic/CDatabaseManager.cpp
  Server/mods/deathmatch/logic/CDatabaseManager.h
  Server/mods/deathmatch/logic/luadefs/CLuaDatabaseDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaDatabaseDefs.h
Labels: enhancement

#1164 Add analog control sync for accelerate and brake_reverse
  Client/mods/deathmatch/logic/CNetAPI.cpp
  Client/version.h
  Server/mods/deathmatch/logic/CPad.cpp
  Server/mods/deathmatch/logic/CPad.h
  Server/mods/deathmatch/logic/Utils.cpp
  Server/version.h
  Shared/sdk/net/SyncStructures.h
Labels: enhancement

#1059 Fix resetting dummies in vehicles with replaced models
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientDFF.cpp
  Client/sdk/game/CModelInfo.h
Labels: bug

#1332 Add cef upgrade script
  utils/buildactions/install_cef.lua
  utils/buildactions/install_discord.lua
  utils/buildactions/utils.lua
Labels: enhancement

#973 Initial version of new style Lua argument parsing
  Client/mods/deathmatch/logic/luadefs/CLuaDefs.h
  Server/mods/deathmatch/StdInc.h
  Server/mods/deathmatch/logic/CGame.h
  Server/mods/deathmatch/logic/luadefs/CLuaDefs.h
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
  Shared/mods/deathmatch/logic/lua/CLuaOverloadParser.h
  Shared/mods/deathmatch/logic/lua/CLuaStackChecker.h
  Shared/mods/deathmatch/logic/lua/LuaBasic.cpp
  Shared/mods/deathmatch/logic/lua/LuaBasic.h
  Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.h
  Shared/sdk/SharedUtil.Template.h
Labels: enhancement

#1327 Update colshape and marker hit detection when attaching
  Client/mods/deathmatch/logic/CClientColShape.cpp
  Client/mods/deathmatch/logic/CClientColShape.h
  Client/mods/deathmatch/logic/CClientMarker.cpp
  Client/mods/deathmatch/logic/CClientMarker.h
  Server/mods/deathmatch/logic/CColShape.cpp
  Server/mods/deathmatch/logic/CColShape.h
  Server/mods/deathmatch/logic/CMarker.cpp
  Server/mods/deathmatch/logic/CMarker.h
Labels: bug

#1350 Fix crash introduced in PR (#1345)
  Client/core/CDiscordManager.cpp
  Client/core/CDiscordManager.h
Labels: bug

#1358 Fix #1357: discord crashes from a4f447ae8047b6d2d65077f093adff69
  Client/core/CCore.cpp
  Client/core/CDiscordManager.cpp
  Client/core/CDiscordManager.h
Labels: bug

#1361 Update CEF to 80.1.15+g7b802c9+chromium-80.0.3987.163
  utils/buildactions/install_cef.lua
Labels: enhancement

#1364 Fix crash from #1363
  Client/mods/deathmatch/logic/CClientMarker.cpp
Labels: bug

#1366 Updated CEF to 81.2.15+ge07275d+chromium-81.0.4044.92 + Fix #1303
  Client/cefweb/CWebCore.cpp
  utils/buildactions/install_cef.lua
Labels: bug

#1372 Fix #1362: xmlLoadString doesn't work
  Shared/XML/CXMLImpl.cpp
Labels: bug

#1384 Added SettingHighDetailPeds to dxGetStatus
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
Labels: enhancement

#1378 Add data installation to CI build
  .github/workflows/build.yaml
Labels: enhancement

#1381 Fix #1106: add the possibility to remove server from recent list
  Client/core/ServerBrowser/CServerBrowser.cpp
  Client/core/ServerBrowser/CServerBrowser.h
Labels: enhancement

#1379 Fix #1292: return vector3 instead of number at ped's target
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
Labels: enhancement

#777 Fix invincible peds
  Client/mods/deathmatch/logic/CClientPed.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug, feedback

#1342 setWaterLevel: added bIncludeWorldSeaLevel and bIncludeOutsideWorldLevel
  Client/game_sa/CWaterManagerSA.cpp
  Client/game_sa/CWaterManagerSA.h
  Client/mods/deathmatch/logic/CClientWaterManager.cpp
  Client/mods/deathmatch/logic/CClientWaterManager.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaWaterDefs.cpp
  Client/mods/deathmatch/logic/rpc/CWaterRPCs.cpp
  Client/sdk/game/CWaterManager.h
  Client/version.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/CWaterManager.cpp
  Server/mods/deathmatch/logic/CWaterManager.h
  Server/mods/deathmatch/logic/luadefs/CLuaWaterDefs.cpp
  Server/mods/deathmatch/logic/packets/CMapInfoPacket.cpp
  Server/mods/deathmatch/logic/packets/CMapInfoPacket.h
  Server/version.h
Labels: enhancement

#1407 Fix #1396: no-op Discord integration
  Client/core/CDiscordManager.cpp
  Client/core/CDiscordManager.h
  Client/core/CSettings.cpp
  Client/core/CSettings.h
  Client/core/premake5.lua
  Shared/data/data files installer.nsi
  Shared/installer/nightly.nsi
  premake5.lua
  vendor/discordgsdk/.gitignore
  vendor/discordgsdk/premake5.lua
  win-create-projects.bat
Labels: refactor

#1413 Remove DEBUG guards for OutputDebugLine
  Client/cefweb/CWebCore.cpp
  Client/cefweb/CWebView.cpp
  Client/core/ServerBrowser/CServerBrowser.RemoteMasterServer.cpp
  Client/core/ServerBrowser/CServerList.cpp
  Server/mods/deathmatch/logic/CPlayer.cpp
Labels: refactor

#1414 Fix #1090 Replaced weapon_crouch anim does not play if retainPedState is true
  Client/game_sa/CAnimBlendAssocGroupSA.cpp
  Client/game_sa/CAnimBlendAssocGroupSA.h
  Client/game_sa/CAnimBlendAssociationSA.h
  Client/game_sa/CAnimManagerSA.cpp
  Client/game_sa/CAnimManagerSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CIFPEngine.cpp
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/multiplayer_sa/CMultiplayerSA_CustomAnimations.cpp
  Client/multiplayer_sa/CMultiplayerSA_FixBadAnimId.cpp
  Client/sdk/game/CAnimBlendAssocGroup.h
  Client/sdk/game/CAnimBlendAssociation.h
  Client/sdk/game/CAnimManager.h
  Client/sdk/multiplayer/CMultiplayer.h
Labels: bug
