Repository multitheftauto/mtasa-blue, pull requests merged in 2020-08, with the labels that each got.

#1541 Add prerequisites to README.md for Windows build
  README.md
Labels: documentation

#1588 Revert "Add engineSet/GetModelTime (#752)"
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
  Client/sdk/game/CGame.h
  Client/sdk/game/CModelInfo.h
  Client/sdk/game/RenderWare.h
Labels: bug

#1555 Add short and char support to the new parser
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
  Shared/mods/deathmatch/logic/lua/LuaBasic.cpp
Labels: enhancement

#1585 Fix return value for ColPolygon procedural functions
  Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
  Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
Labels: bug

#1595 Fix #1581: dxDrawPrimitive wrong colors with alpha <255
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Shared/sdk/CScriptArgReader.h
Labels: bug

#1600 Revert "Fix #578: doors state with setElementModel (#599)"
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Server/mods/deathmatch/logic/CVehicle.cpp
Labels: bug

#1601 Fix #1171: setElementVisibleTo return value
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#1619 Revert "Fix #1443 - trim teaEncode trailing zeroes"
  Shared/sdk/SharedUtil.Hash.h
  Shared/sdk/SharedUtil.Hash.hpp
Labels: bug

#1623 Fix #1617: Vehicle DFF leak fix disabled
  Client/game_sa/CRenderWareSA.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
Labels: bug

#1602 Fix debugscript setting to 0 when using invalid characters
  Server/mods/deathmatch/logic/CConsoleCommands.cpp
Labels: bug

#1627 Security Fix: SMods can perform escalation attack
  Server/mods/deathmatch/acl.xml
Labels: enhancement

#1638 Remove client entity check from setPedArmor
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
Labels: bug

#1640 Add vehicle dff leak fix back
  Client/game_sa/CRenderWareSA.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
Labels: bug

#1644 Add get/setVehicleModelWheelSize
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientDFF.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Client/sdk/game/CModelInfo.h
  Client/sdk/game/Common.h
  Shared/mods/deathmatch/logic/lua/LuaBasic.h
Labels: enhancement
