Repository multitheftauto/mtasa-blue, pull requests merged in 2020-10, with the labels that each got.

#1694 Revert "Revert "Use long long as Lua integer formatting type""
  vendor/lua/src/luaconf.h
Labels: bug

#1697 Update BASS libraries
  Client/loader/MainFunctions.cpp
  Shared/data/MTA San Andreas/MTA/bass.dll
  Shared/data/MTA San Andreas/MTA/bassmidi.dll
  vendor/bass/bass.h
Labels: upstream

#1606 Update unrar from 5.71 to 5.91
  vendor/unrar/arccmt.cpp
  vendor/unrar/archive.cpp
  vendor/unrar/archive.hpp
  vendor/unrar/arcread.cpp
  vendor/unrar/blake2s.hpp
  vendor/unrar/cmddata.cpp
  vendor/unrar/cmddata.hpp
  vendor/unrar/cmdfilter.cpp
  vendor/unrar/crc.cpp
  vendor/unrar/dll.cpp
  vendor/unrar/dll.rc
  vendor/unrar/errhnd.cpp
  vendor/unrar/extract.cpp
  vendor/unrar/file.cpp
  vendor/unrar/file.hpp
  vendor/unrar/filefn.cpp
  vendor/unrar/find.cpp
  vendor/unrar/hash.cpp
  vendor/unrar/list.cpp
  vendor/unrar/loclang.hpp
  vendor/unrar/makefile
  vendor/unrar/options.cpp
  vendor/unrar/options.hpp
  vendor/unrar/os.hpp
  vendor/unrar/pathfn.cpp
  vendor/unrar/qopen.cpp
  vendor/unrar/rar.hpp
  vendor/unrar/rartypes.hpp
  vendor/unrar/rdwrfn.hpp
  vendor/unrar/recvol.cpp
  vendor/unrar/recvol.hpp
  vendor/unrar/recvol3.cpp
  vendor/unrar/recvol5.cpp
  vendor/unrar/resource.cpp
  vendor/unrar/rijndael.cpp
  vendor/unrar/savepos.hpp
  vendor/unrar/strfn.cpp
  vendor/unrar/system.cpp
  vendor/unrar/threadmisc.cpp
  vendor/unrar/threadpool.cpp
  vendor/unrar/threadpool.hpp
  vendor/unrar/ui.hpp
  vendor/unrar/uiconsole.cpp
  vendor/unrar/unicode.cpp
  vendor/unrar/unicode.hpp
  vendor/unrar/unpack.cpp
  vendor/unrar/unpack.hpp
  vendor/unrar/unpack50.cpp
  vendor/unrar/version.hpp
  vendor/unrar/win32acl.cpp
  vendor/unrar/win32stm.cpp
Labels: enhancement, upstream

#1706 Update CResourceChecker.Data.cpp for 1.5.8's features
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
Labels: documentation

#1704 Fix engineGetModelTextures memory leak
  Client/core/CCredits.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
Labels: bug

#1713 Delete getTrainTrack and setTrainTrack
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
Labels: enhancement

#1712 Fix #1708: Force people to opt back into Default release type
  Client/core/CMainMenu.cpp
  Client/core/CVersionUpdater.cpp
  Client/core/CVersionUpdater.h
Labels: enhancement

#1716 Save server row index instead of finding it
  Client/core/ServerBrowser/CServerBrowser.cpp
  Client/core/ServerBrowser/CServerBrowser.h
  Client/core/ServerBrowser/CServerList.h
Labels: enhancement

#1717 Refactor CVehicleSAInterface
  Client/game_sa/CAutomobileSA.cpp
  Client/game_sa/CAutomobileSA.h
  Client/game_sa/CDamageManagerSA.h
  Client/game_sa/CDoorSA.h
  Client/game_sa/CTrainSA.cpp
  Client/game_sa/CTrainSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
  Client/game_sa/StdInc.h
  Client/multiplayer_sa/CMultiplayerSA_CrashFixHacks.cpp
Labels: refactor

#1715 Custom train tracks: initial server awareness
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Server/mods/deathmatch/StdInc.h
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CGame.h
  Server/mods/deathmatch/logic/CTrainTrack.cpp
  Server/mods/deathmatch/logic/CTrainTrack.h
  Server/mods/deathmatch/logic/CTrainTrackManager.cpp
  Server/mods/deathmatch/logic/CTrainTrackManager.h
  Server/mods/deathmatch/logic/CVehicle.cpp
  Server/mods/deathmatch/logic/CVehicle.h
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Server/mods/deathmatch/logic/packets/CVehiclePuresyncPacket.cpp
  Server/mods/deathmatch/premake5.lua
  Shared/gta/TrackNodes.h
  Shared/mods/deathmatch/logic/lua/CLuaShared.cpp
  Shared/mods/deathmatch/logic/lua/CLuaShared.h
  Shared/mods/deathmatch/logic/luadefs/CLuaTrainTrackDefs.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaTrainTrackDefs.h
Labels: enhancement

#1518 Add getRoofPosition
  Client/game_sa/CWorldSA.cpp
  Client/game_sa/CWorldSA.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.World.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.h
  Client/mods/deathmatch/logic/lua/CLuaManager.cpp
  Client/sdk/game/CWorld.h
Labels: enhancement

#1398 Allow to use peds and vehicles as a camera target
  Client/mods/deathmatch/logic/CNetAPI.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
  Client/mods/deathmatch/logic/rpc/CCameraRPCs.cpp
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
Labels: enhancement

#1733 Fix #1724: setPedAnimation breaks setChoking and setWearingJetpack in the same frame
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#1729 Change getRoofPosition fail from warning to error
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.World.cpp
Labels: bug

#1731 Move client-side world functions to CLuaWorldDefs
  Client/mods/deathmatch/StdInc.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.h
  Client/mods/deathmatch/logic/lua/CLuaManager.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaNetworkDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaNetworkDefs.h
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.h
Labels: hacktoberfest-accepted, refactor

#1734 Fix #1730: Wrong SQLite column in getAccountsByIP
  Server/mods/deathmatch/logic/CAccountManager.cpp
Labels: bug

#1739 Add missing CLuaNetworkDefs::LoadFunctions on client-side
  Client/mods/deathmatch/logic/lua/CLuaManager.cpp
Labels: bug

#1741 Revert "Allow to use peds and vehicles as a camera target (#1398)"
  Client/mods/deathmatch/logic/CNetAPI.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
  Client/mods/deathmatch/logic/rpc/CCameraRPCs.cpp
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
Labels: bug

#1573 Support for passing macros to a shader
  Client/core/Graphics/CRenderItem.EffectCloner.cpp
  Client/core/Graphics/CRenderItem.EffectCloner.h
  Client/core/Graphics/CRenderItem.EffectTemplate.cpp
  Client/core/Graphics/CRenderItem.EffectTemplate.h
  Client/core/Graphics/CRenderItem.Shader.cpp
  Client/core/Graphics/CRenderItemManager.cpp
  Client/core/Graphics/CRenderItemManager.h
  Client/mods/deathmatch/logic/CClientRenderElementManager.cpp
  Client/mods/deathmatch/logic/CClientRenderElementManager.h
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Client/sdk/core/CRenderItemManagerInterface.h
  Shared/sdk/CScriptArgReader.h
Labels: enhancement

#1478 Refactor CVector/2D/4D to use constexpr + noexcept everywhere
  Shared/sdk/CVector.h
  Shared/sdk/CVector2D.h
  Shared/sdk/CVector4D.h
Labels: refactor

#1604 Hide encode function's secret key in debughooks
  Shared/mods/deathmatch/logic/CDebugHookManager.cpp
Labels: enhancement

#1738 Move remote functions to CLuaNetworkDefs on server-side
  Server/mods/deathmatch/StdInc.h
  Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.Server.cpp
  Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.h
  Server/mods/deathmatch/logic/lua/CLuaManager.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaNetworkDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaNetworkDefs.h
Labels: refactor

#1737 Use enum classes for BitStream
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/sdk/net/CNet.h
  Client/version.h
  Server/mods/deathmatch/logic/CPlayer.h
  Server/version.h
  Shared/sdk/net/bitstream.h
Labels: hacktoberfest-accepted, refactor

#1599 Fix #727: Add client-side setVehicleVariant
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
Labels: enhancement

#1752 Make sure BitStream comparisons still work correctly
  Shared/sdk/net/bitstream.h
Labels: bug

#1761 Fix game freeze & updated BASS libraries
  Client/loader/MainFunctions.cpp
  Shared/data/MTA San Andreas/MTA/bass.dll
  Shared/data/MTA San Andreas/MTA/bass_aac.dll
  Shared/data/MTA San Andreas/MTA/bass_fx.dll
Labels: bug, upstream

#1763 Fix crash when deleting a chatbox bind too early
  Client/core/CKeyBinds.cpp
Labels: bug

#1735 Add engineRestreamWorld function
  Client/game_sa/CStreamingSA.cpp
  Client/game_sa/CStreamingSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/CClientObjectManager.cpp
  Client/mods/deathmatch/logic/CClientObjectManager.h
  Client/mods/deathmatch/logic/CClientPedManager.cpp
  Client/mods/deathmatch/logic/CClientPedManager.h
  Client/mods/deathmatch/logic/CClientPickupManager.cpp
  Client/mods/deathmatch/logic/CClientPickupManager.h
  Client/mods/deathmatch/logic/CClientVehicleManager.cpp
  Client/mods/deathmatch/logic/CClientVehicleManager.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/multiplayer_sa/CMultiplayerSA_Streaming.cpp
  Client/sdk/game/CStreaming.h
Labels: enhancement, hacktoberfest-accepted

#1755 Add minimum version check for resetBlurLevel
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
Labels: bug, hacktoberfest-accepted

#1673 New bone functions and onClientPedsProcessed event
  Client/game_sa/BoneNode_cSA.cpp
  Client/game_sa/BoneNode_cSA.h
  Client/game_sa/CAnimBlendAssociationSA.cpp
  Client/game_sa/CAnimBlendAssociationSA.h
  Client/game_sa/CEntitySA.cpp
  Client/game_sa/CEntitySA.h
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CMatrixSA.cpp
  Client/game_sa/CMatrixSA.h
  Client/game_sa/CPedIKSA.cpp
  Client/game_sa/CPedIKSA.h
  Client/game_sa/CPedSA.h
  Client/game_sa/CRenderWareSA.cpp
  Client/game_sa/CRenderWareSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/StdInc.h
  Client/game_sa/gamesa_renderware.h
  Client/game_sa/gamesa_renderware.hpp
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/sdk/game/CEntity.h
  Client/sdk/game/CPed.h
  Client/sdk/game/CPedIK.h
  Client/sdk/game/CRenderWare.h
  Client/sdk/game/RenderWare.h
  Client/sdk/multiplayer/CMultiplayer.h
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
  Shared/mods/deathmatch/logic/lua/LuaBasic.h
  Shared/sdk/CMatrix.h
Labels: enhancement

#1437 Fix #1436: getValidPedModels() to include engineRequestModel skins as well
  Client/mods/deathmatch/logic/CClientModel.h
  Client/mods/deathmatch/logic/CClientModelManager.cpp
  Client/mods/deathmatch/logic/CClientModelManager.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Util.cpp
Labels: bug

#1766 Fix engineSet/GetModelTime don't work in release
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
  Client/sdk/game/CGame.h
  Client/sdk/game/CModelInfo.h
Labels: bug, enhancement

#1749 Apply enum classes to existing BitStream code
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CNetAPI.cpp
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/rpc/CPedRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CVehicleRPCs.cpp
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/packets/CChatEchoPacket.cpp
  Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp
  Server/mods/deathmatch/logic/packets/CPlayerJoinCompletePacket.cpp
  Server/mods/deathmatch/logic/packets/CPlayerJoinDataPacket.cpp
  Server/mods/deathmatch/logic/packets/CPlayerListPacket.cpp
  Server/mods/deathmatch/logic/packets/CSyncSettingsPacket.cpp
  Shared/mods/deathmatch/logic/Utils.cpp
  Shared/sdk/net/SyncStructures.h
  Shared/sdk/net/bitstream.h
Labels: refactor

#1639 Fix #406: improve help command in server console
  Server/mods/deathmatch/logic/CConsole.cpp
  Server/mods/deathmatch/logic/CConsole.h
  Server/mods/deathmatch/logic/CConsoleCommand.cpp
  Server/mods/deathmatch/logic/CConsoleCommand.h
  Server/mods/deathmatch/logic/CConsoleCommands.cpp
  Server/mods/deathmatch/logic/CMainConfig.cpp
  Server/mods/deathmatch/logic/CMainConfig.h
Labels: enhancement
