Repository multitheftauto/mtasa-blue, pull requests merged in 2020-09, with the labels that each got.

#1668 Fix #1659: attached markers having 2 ids causes server crash
  Client/mods/deathmatch/logic/CClientEntity.h
  Client/mods/deathmatch/logic/CClientMarker.cpp
  Client/mods/deathmatch/logic/CClientPickup.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CMarker.cpp
  Server/mods/deathmatch/logic/CPickup.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#1663 Fix stack overflow when attaching elements in maps
  Client/mods/deathmatch/logic/CClientEntity.cpp
  Client/mods/deathmatch/logic/CClientEntity.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CElement.cpp
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CMapManager.cpp
  Server/mods/deathmatch/logic/CResourceMapItem.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#1637 Update cryptopp from 8.1.0 to 8.2.0
  vendor/cryptopp/Doxyfile
  vendor/cryptopp/Filelist.txt
  vendor/cryptopp/GNUmakefile
  vendor/cryptopp/GNUmakefile-cross
  vendor/cryptopp/History.txt
  vendor/cryptopp/Readme.txt
  vendor/cryptopp/blake2.cpp
  vendor/cryptopp/blake2.h
  vendor/cryptopp/blake2b_simd.cpp
  vendor/cryptopp/blake2s_simd.cpp
  vendor/cryptopp/chacha.cpp
  vendor/cryptopp/chacha_simd.cpp
  vendor/cryptopp/config.h
  vendor/cryptopp/cpu.cpp
  vendor/cryptopp/cryptdll.vcxproj
  vendor/cryptopp/cryptdll.vcxproj.filters
  vendor/cryptopp/cryptest.nmake
  vendor/cryptopp/cryptlib.h
  vendor/cryptopp/cryptopp.rc
  vendor/cryptopp/datatest.cpp
  vendor/cryptopp/filters.h
  vendor/cryptopp/gcm.cpp
  vendor/cryptopp/gcm_simd.cpp
  vendor/cryptopp/gf2n_simd.cpp
  vendor/cryptopp/integer.cpp
  vendor/cryptopp/keccak_simd.cpp
  vendor/cryptopp/misc.h
  vendor/cryptopp/ppc_simd.h
  vendor/cryptopp/rdrand.s
  vendor/cryptopp/regtest3.cpp
  vendor/cryptopp/seckey.h
  vendor/cryptopp/shake.h
  vendor/cryptopp/simon.cpp
  vendor/cryptopp/simon128_simd.cpp
  vendor/cryptopp/simon64_simd.cpp
  vendor/cryptopp/skipjack.h
  vendor/cryptopp/speck.cpp
  vendor/cryptopp/speck128_simd.cpp
  vendor/cryptopp/speck64_simd.cpp
  vendor/cryptopp/validat5.cpp
  vendor/cryptopp/xed25519.h
Labels: enhancement, upstream

#1675 Add support for CLuaArguments return type to the new parser
  Client/mods/deathmatch/logic/lua/CLuaArguments.cpp
  Client/mods/deathmatch/logic/lua/CLuaArguments.h
  Server/mods/deathmatch/logic/lua/CLuaArguments.cpp
  Server/mods/deathmatch/logic/lua/CLuaArguments.h
  Shared/mods/deathmatch/logic/lua/LuaBasic.h
Labels: enhancement

#1685 Revert "Fix stack overflow when attaching elements in maps"
  Client/mods/deathmatch/logic/CClientEntity.cpp
  Client/mods/deathmatch/logic/CClientEntity.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CElement.cpp
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CMapManager.cpp
  Server/mods/deathmatch/logic/CResourceMapItem.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#1690 Revert "Revert "Fix stack overflow when attaching elements in maps""
  Client/mods/deathmatch/logic/CClientEntity.cpp
  Client/mods/deathmatch/logic/CClientEntity.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CElement.cpp
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CMapManager.cpp
  Server/mods/deathmatch/logic/CResourceMapItem.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#1691 Revert "Use long long as Lua integer formatting type"
  vendor/lua/src/luaconf.h
Labels: bug
