Repository multitheftauto/mtasa-blue, pull requests merged in 2020-03, with the labels that each got.

#1270 Re-enable vs2019
  .github/workflows/build.yaml
  premake5.lua
  win-build.bat
  win-create-projects.bat
Labels: enhancement

#1287 Fix signed/unsigned mismatch warnings introduced in #1215
  Client/mods/deathmatch/logic/CClientColPolygon.cpp
  Client/mods/deathmatch/logic/CClientColPolygon.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
  Client/mods/deathmatch/logic/rpc/CColShapeRPCs.cpp
  Server/mods/deathmatch/logic/CColPolygon.cpp
  Server/mods/deathmatch/logic/CColPolygon.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
Labels: bug

#1163 Add hasElementData Lua feature to client and serverside
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
  Shared/mods/deathmatch/logic/luadefs/CLuaElementDefsShared.cpp
Labels: enhancement

#935 Add dxGetTextSize function
  Client/core/Graphics/CGraphics.cpp
  Client/core/Graphics/CGraphics.h
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.h
  Client/sdk/core/CGraphicsInterface.h
Labels: enhancement

#1290 Fix #1279: driveby for peds
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#892 Add more data to getPedAnimation
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CClientPed.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
Labels: enhancement

#1266 Add clientside lua function resetBlurLevel
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.World.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.h
  Client/mods/deathmatch/logic/lua/CLuaManager.cpp
Labels: enhancement

#1306 Add CVAR _beta_qc_rightclick_command
  Client/core/CClientVariables.cpp
  Client/core/CMainMenu.cpp
  Client/core/CMainMenu.h
  Client/gui/CGUIElement_Impl.cpp
  Client/gui/CGUIElement_Impl.h
  Client/gui/CGUIElement_Inc.h
  Client/gui/CGUI_Impl.cpp
  Client/sdk/gui/CGUIElement.h
Labels: enhancement

#1312 Fix #1299 and #1148: Primitive colors are always white
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
Labels: bug

#1234 Add ability to play sounds from raw data to playSound(3D)
  Client/mods/deathmatch/logic/CClientSoundManager.cpp
  Client/mods/deathmatch/logic/CClientSoundManager.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.cpp
Labels: enhancement

#960 Don't queue a resource restart if resource is stopping
  Server/mods/deathmatch/logic/luadefs/CLuaResourceDefs.cpp
Labels: enhancement

#599 Fix #578: doors state with setElementModel
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Server/mods/deathmatch/logic/CVehicle.cpp
Labels: bug, question

#1307 ci: bump checkout action to v2
  .github/workflows/build.yaml
Labels: enhancement

#1324 Fix crash when we can't connect to Discord
  Client/core/CDiscordManager.cpp
Labels: bug

#1298 Download CEF from opensource.spotify.com
  utils/buildactions/install_cef.lua
  utils/buildactions/install_discord.lua
  utils/buildactions/utils.lua
Labels: enhancement

#945 downloadFile: downloading from another resource
  Client/mods/deathmatch/logic/CSingularFileDownload.cpp
  Client/mods/deathmatch/logic/CSingularFileDownload.h
  Client/mods/deathmatch/logic/CSingularFileDownloadManager.cpp
  Client/mods/deathmatch/logic/CSingularFileDownloadManager.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Util.cpp
Labels: enhancement, feedback

#1254 Add isResourceProtected function
  Server/mods/deathmatch/logic/luadefs/CLuaResourceDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaResourceDefs.h
Labels: enhancement
