Repository multitheftauto/mtasa-blue, pull requests merged in 2021-04, with the labels that each got.

#2146 Add lua_getowner for fast access to owner resource
  Client/mods/deathmatch/logic/lua/CLuaMain.cpp
  Client/mods/deathmatch/logic/lua/LuaCommon.cpp
  Client/mods/deathmatch/logic/lua/LuaCommon.h
  Server/mods/deathmatch/logic/lua/CLuaMain.cpp
  Server/mods/deathmatch/logic/lua/LuaCommon.cpp
  Server/mods/deathmatch/logic/lua/LuaCommon.h
  Server/mods/deathmatch/logic/luadefs/CLuaDefs.cpp
  vendor/lua/src/lapi.c
  vendor/lua/src/lauxlib.c
  vendor/lua/src/lauxlib.h
  vendor/lua/src/lstate.c
  vendor/lua/src/lstate.h
  vendor/lua/src/lua.h
Labels: enhancement

#2110 Use new argument parser for generic server functions
  Server/mods/deathmatch/logic/CMainConfig.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.Server.cpp
  Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.h
  Server/mods/deathmatch/logic/lua/CLuaManager.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.h
  Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaTeamDefs.cpp
  Shared/mods/deathmatch/logic/lua/LuaBasic.h
Labels: enhancement

#1418 Allow to change player camera mode
  Client/game_sa/CCameraSA.cpp
  Client/game_sa/CCameraSA.h
  Client/mods/deathmatch/logic/CClientCamera.cpp
  Client/mods/deathmatch/logic/CClientCamera.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.h
  Client/sdk/game/CCamera.h
Labels: enhancement

#2040 Refactor passwordHash to use the new argument parser
  Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.h
Labels: refactor

#2160 Add clearDebugBox
  Client/mods/deathmatch/logic/luadefs/CLuaClientDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaClientDefs.h
Labels: enhancement

#1978 Fix #741: Add new CServerRPCControlPacket to toggle RPCs from server
  Client/mods/deathmatch/StdInc.h
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/CNetAPI.cpp
  Client/mods/deathmatch/logic/CNetAPI.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CPacketHandler.h
  Client/mods/deathmatch/logic/rpc/CRPCFunctions.cpp
  Server/mods/deathmatch/StdInc.h
  Server/mods/deathmatch/logic/CEvents.cpp
  Server/mods/deathmatch/logic/CEvents.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CMapEventManager.cpp
  Server/mods/deathmatch/logic/CMapEventManager.h
  Server/mods/deathmatch/logic/CPerfStat.RPCPacketUsage.cpp
  Server/mods/deathmatch/logic/CRPCFunctions.h
  Server/mods/deathmatch/logic/packets/CServerRPCControlPacket.cpp
  Server/mods/deathmatch/logic/packets/CServerRPCControlPacket.h
  Shared/mods/deathmatch/logic/Enums.cpp
  Shared/mods/deathmatch/logic/Enums.h
  Shared/sdk/net/Packets.h
  Shared/sdk/net/rpc_enums.h
Labels: enhancement

#2199 Fix #2183: Tweak bind queue logic
  Client/core/CKeyBinds.cpp
Labels: bug

#2201 Update BASS libraries
  Client/loader/MainFunctions.cpp
  Shared/data/MTA San Andreas/MTA/bass.dll
  Shared/data/MTA San Andreas/MTA/bassflac.dll
  Shared/data/MTA San Andreas/MTA/bassmidi.dll
  Shared/data/MTA San Andreas/MTA/bassmix.dll
Labels: enhancement, upstream

#2193 An option to flip UV on material lines
  Client/core/Graphics/CGraphics.cpp
  Client/core/Graphics/CGraphics.h
  Client/core/Graphics/CMaterialLine3DBatcher.cpp
  Client/core/Graphics/CMaterialLine3DBatcher.h
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Client/sdk/core/CGraphicsInterface.h
Labels: enhancement

#2192 Fix #2178: testLineAgainstWater works incorrectly outside of game boundaries
  Client/game_sa/CWaterManagerSA.cpp
  Shared/sdk/CVector.h
Labels: bug
