Repository multitheftauto/mtasa-blue, pull requests merged in 2021-08, with the labels that each got.

#2269 Add engineStreamingGetUsedMemory
  Client/game_sa/CStreamingSA.cpp
  Client/game_sa/CStreamingSA.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/sdk/game/CStreaming.h
Labels: enhancement

#2268 Add engineStreamingFreeUpMemory
  Client/game_sa/CStreamingSA.cpp
  Client/game_sa/CStreamingSA.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/sdk/game/CStreaming.h
Labels: enhancement

#2264 Increase streaming memory setting limit
  Client/core/CCore.cpp
Labels: enhancement

#2253 Add a UI button to delete servers from the "Recent" tab
  Client/core/ServerBrowser/CServerBrowser.cpp
  Client/core/ServerBrowser/CServerBrowser.h
  Shared/data/MTA San Andreas/MTA/cgui/images/serverbrowser/trashcan.png
Labels: enhancement

#2283 Update CEF to 92.0.21+ga9ec100+chromium-92.0.4515.107
  utils/buildactions/install_cef.lua
Labels: enhancement, upstream

#2124 Trim keybind whitespace to avoid duplicates
  Client/core/CKeyBinds.cpp
  Shared/sdk/SharedUtil.Misc.h
  Shared/sdk/SharedUtil.Misc.hpp
Labels: enhancement

#1020 Implement messageType parameter to onClientChatMessage
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Server/mods/deathmatch/logic/CConsoleCommands.cpp
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CPlayer.cpp
  Server/mods/deathmatch/logic/packets/CChatEchoPacket.cpp
  Server/mods/deathmatch/logic/packets/CChatEchoPacket.h
  Shared/sdk/net/bitstream.h
Labels: enhancement

#2292 Fix info command displaying two statuses of a running resource
  Server/mods/deathmatch/logic/CResource.cpp
Labels: bug

#642 Add functions to change sound effect parameters
  Client/mods/deathmatch/logic/CBassAudio.cpp
  Client/mods/deathmatch/logic/CBassAudio.h
  Client/mods/deathmatch/logic/CClientPlayerVoice.h
  Client/mods/deathmatch/logic/CClientSound.cpp
  Client/mods/deathmatch/logic/CClientSound.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.h
  Client/sdk/game/Common.h
Labels: enhancement

#2298 Add exit code to shutdown function (Fixes #2293)
  Server/core/CModManagerImpl.cpp
  Server/core/CModManagerImpl.h
  Server/core/CServerImpl.cpp
  Server/core/CServerImpl.h
  Server/core/Server.cpp
  Server/mods/deathmatch/StdInc.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/lua/CLuaFunctionDefs.cpp
  Server/mods/deathmatch/logic/lua/CLuaMain.cpp
  Server/mods/deathmatch/logic/lua/CLuaMain.h
  Server/mods/deathmatch/logic/lua/CLuaManager.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaDefs.h
  Server/mods/deathmatch/logic/luadefs/CLuaFunctionDefs.Clothing.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaFunctionDefs.Event.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaFunctionDefs.Misc.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaFunctionDefs.Server.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaFunctionDefs.Weapon.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaFunctionDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaFunctionDefs.h
  Server/sdk/core/CModManager.h
  Shared/mods/deathmatch/logic/CLatentTransferManager.cpp
Labels: enhancement

#2296 Resolve remaining collisionless objects (Fixes #927)
  Client/game_sa/CColLineSA.h
  Client/game_sa/CColModelSA.h
  Client/game_sa/CColStoreSA.cpp
  Client/game_sa/CColStoreSA.h
  Client/game_sa/CEntitySA.cpp
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/game_sa/CPhysicalSA.cpp
  Client/game_sa/CStreamingSA.cpp
  Client/game_sa/CStreamingSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/gamesa_renderware.h
  Client/mods/deathmatch/logic/CClientColModel.cpp
  Client/mods/deathmatch/logic/CClientColModel.h
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/multiplayer_sa/CMultiplayerSA_1.3.cpp
  Client/multiplayer_sa/CMultiplayerSA_ObjectCollision.cpp
  Client/sdk/game/CColModel.h
  Client/sdk/game/CColStore.h
  Client/sdk/game/CGame.h
  Client/sdk/game/CModelInfo.h
  Client/sdk/game/CStreaming.h
Labels: bug

#2290 Fix #2127: Attached players desync after reconnect
  Client/mods/deathmatch/logic/CPacketHandler.cpp
Labels: bug

#2295 Remove unused code in CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
Labels: enhancement

#2305 Fix onClientElementInteriorChange is triggered even if the element already in the same interior
  Client/mods/deathmatch/logic/CClientEntity.cpp
Labels: bug

#2310 Fix #2280: onClientElementInteriorChange is triggered even if the element has not changed its interior
  Client/mods/deathmatch/logic/CClientEntity.cpp
Labels: bug

#2308 Add is/setPedBleeding functions
  Client/game_sa/CPedSA.cpp
  Client/game_sa/CPedSA.h
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CClientPed.h
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
  Client/sdk/game/CPed.h
Labels: enhancement
