Repository multitheftauto/mtasa-blue, pull requests merged in 2021-09, with the labels that each got.

#2323 Revert "Increase streaming memory setting limit (#2264)"
  Client/core/CCore.cpp
Labels: bug

#2344 Fix #2335: Don't allow dead peds to enter vehicles
  Server/mods/deathmatch/logic/CGame.cpp
Labels: bug

#1711 Add intersectsSegmentTriangle method to Vector3
  Shared/mods/deathmatch/logic/luadefs/CLuaVector3Defs.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaVector3Defs.h
Labels: enhancement

#2315 Add getPlayerMapOpacity function
  Client/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.h
Labels: enhancement

#2353 Typo fix in remotely
  Client/loader/Utils.cpp
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/multiplayer_sa/multiplayer_keysync.cpp
  Server/mods/deathmatch/logic/CGame.cpp
  Shared/mods/deathmatch/logic/Utils.cpp
Labels: bug

#2150 Add onPlayerResourceStart event
  Client/mods/deathmatch/logic/CResource.cpp
  Server/mods/deathmatch/StdInc.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CGame.h
  Server/mods/deathmatch/logic/CPacketTranslator.cpp
  Server/mods/deathmatch/logic/packets/CPlayerResourceStartPacket.cpp
  Server/mods/deathmatch/logic/packets/CPlayerResourceStartPacket.h
  Shared/mods/deathmatch/logic/Enums.cpp
  Shared/sdk/net/Packets.h
  Shared/sdk/net/bitstream.h
Labels: enhancement

#2355 Fix #611: Add line spacing to dxDrawText #2209
  Client/core/Graphics/CGraphics.cpp
  Client/core/Graphics/CGraphics.h
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Client/sdk/core/CGraphicsInterface.h
Labels: enhancement

#2365 Fix some ped bleeding issues
  Client/mods/deathmatch/logic/CClientPed.cpp
Labels: bug

#2373 Update curl from 7.79.0 to 7.79.1
  vendor/curl/CHANGES
  vendor/curl/RELEASE-NOTES
  vendor/curl/include/curl/curlver.h
  vendor/curl/lib/hsts.c
  vendor/curl/lib/hsts.h
  vendor/curl/lib/http.c
  vendor/curl/lib/http2.c
  vendor/curl/lib/multi.c
  vendor/curl/lib/select.h
  vendor/curl/lib/strerror.c
  vendor/curl/lib/transfer.c
Labels: enhancement, upstream

#1753 Allow to use peds and vehicles as a camera target (with fixes)
  Client/mods/deathmatch/logic/CClientCamera.cpp
  Client/mods/deathmatch/logic/CClientCamera.h
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CNetAPI.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
  Client/mods/deathmatch/logic/rpc/CCameraRPCs.cpp
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
Labels: bug

#2378 Fix missing return values (#2026)
  Client/mods/deathmatch/logic/luadefs/CLuaVectorGraphicDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVectorGraphicDefs.h
Labels: bug

#2384 Update unrar from 5.91 to 6.02
  vendor/unrar/acknow.txt
  vendor/unrar/arcread.cpp
  vendor/unrar/cmddata.cpp
  vendor/unrar/cmddata.hpp
  vendor/unrar/consio.cpp
  vendor/unrar/dll.cpp
  vendor/unrar/dll.def
  vendor/unrar/dll.rc
  vendor/unrar/dll_nocrypt.def
  vendor/unrar/errhnd.cpp
  vendor/unrar/errhnd.hpp
  vendor/unrar/extinfo.hpp
  vendor/unrar/extract.cpp
  vendor/unrar/extract.hpp
  vendor/unrar/filcreat.cpp
  vendor/unrar/file.cpp
  vendor/unrar/file.hpp
  vendor/unrar/filefn.cpp
  vendor/unrar/filefn.hpp
  vendor/unrar/hardlinks.cpp
  vendor/unrar/list.cpp
  vendor/unrar/loclang.hpp
  vendor/unrar/makefile
  vendor/unrar/options.hpp
  vendor/unrar/pathfn.cpp
  vendor/unrar/savepos.hpp
  vendor/unrar/secpassword.cpp
  vendor/unrar/ui.hpp
  vendor/unrar/uiconsole.cpp
  vendor/unrar/uisilent.cpp
  vendor/unrar/ulinks.cpp
  vendor/unrar/unicode.cpp
  vendor/unrar/version.hpp
  vendor/unrar/volume.cpp
  vendor/unrar/win32lnk.cpp
Labels: enhancement, upstream

#2381 Update resource checker version data
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
Labels: enhancement, help wanted

#2388 Fix some SVG issues
  Client/mods/deathmatch/logic/CClientPerfStat.LuaMemory.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
Labels: bug
