Repository multitheftauto/mtasa-blue, pull requests merged in 2021-02, with the labels that each got.

#2031 Add ToString to CXMLNodeImpl
  Shared/XML/CXMLNodeImpl.cpp
  Shared/XML/CXMLNodeImpl.h
  Shared/sdk/xml/CXMLNode.h
Labels: enhancement

#2068 Remove unused hwbrk library
  Client/core/CCore.cpp
  Client/core/CCore.h
  Client/core/CCrashDumpWriter.cpp
  Client/core/CCrashDumpWriter.h
  Client/core/StdInc.h
  Client/core/premake5.lua
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/StdInc.h
  Client/multiplayer_sa/multiplayersa_init.cpp
  Client/multiplayer_sa/premake5.lua
  Client/sdk/core/CCoreInterface.h
  premake5.lua
  vendor/hwbrk/hwbrk.cpp
  vendor/hwbrk/hwbrk.h
  vendor/hwbrk/premake5.lua
Labels: enhancement, upstream

#2022 Update detours library to version 4.0.1
  Client/core/CCore.cpp
  Client/core/CSetCursorPosHook.cpp
  Client/core/CrashHandler.cpp
  Client/core/DXHook/CDirect3DHook9.cpp
  Client/core/DXHook/CDirectInputHook8.cpp
  Client/core/premake5.lua
  Client/loader/premake5.lua
  Server/core/CCrashHandlerAPI.cpp
  Server/core/premake5.lua
  Shared/sdk/SharedUtil.Detours.h
  Shared/sdk/SharedUtil.Win32Utf8FileHooks.hpp
  premake5.lua
  vendor/detours/4.0.1/CREDITS.TXT
  vendor/detours/4.0.1/LICENSE.md
  vendor/detours/4.0.1/src/creatwth.cpp
  vendor/detours/4.0.1/src/detours.cpp
  vendor/detours/4.0.1/src/detours.h
  vendor/detours/4.0.1/src/detver.h
  vendor/detours/4.0.1/src/disasm.cpp
  vendor/detours/4.0.1/src/disolarm.cpp
  vendor/detours/4.0.1/src/disolarm64.cpp
  vendor/detours/4.0.1/src/disolia64.cpp
  vendor/detours/4.0.1/src/disolx64.cpp
  vendor/detours/4.0.1/src/disolx86.cpp
  vendor/detours/4.0.1/src/image.cpp
  vendor/detours/4.0.1/src/modules.cpp
  vendor/detours/4.0.1/src/uimports.cpp
  vendor/detours/LICENSE.TXT
  vendor/detours/REDIST.TXT
  vendor/detours/include/detours.h
  vendor/detours/lib/detours.lib
  vendor/detours/lib/detours.pdb
  vendor/detours/premake5.lua
Labels: enhancement, upstream

#2083 Fix object position return in processLineOfSight
  Client/game_sa/CWorldSA.cpp
Labels: bug
