Repository multitheftauto/mtasa-blue, pull requests merged in 2021-11, with the labels that each got.

#2399 Fix #868, #1662 and #1740: Fix sync of light states (damage) and wheel states
  Server/mods/deathmatch/logic/CGame.cpp
Labels: bug

#2431 Fix small memory leak for engineRequestModel
  Client/game_sa/CModelInfoSA.cpp
Labels: bug

#2439 Update libspeex to 1.2 and libspeexdsp to 1.2rc3
  vendor/libspeex/libspeex/arch.h
  vendor/libspeex/libspeex/bits.c
  vendor/libspeex/libspeex/cb_search.c
  vendor/libspeex/libspeex/exc_10_16_table.c
  vendor/libspeex/libspeex/exc_10_32_table.c
  vendor/libspeex/libspeex/exc_20_32_table.c
  vendor/libspeex/libspeex/exc_5_256_table.c
  vendor/libspeex/libspeex/exc_5_64_table.c
  vendor/libspeex/libspeex/exc_8_128_table.c
  vendor/libspeex/libspeex/filters.c
  vendor/libspeex/libspeex/gain_table.c
  vendor/libspeex/libspeex/gain_table_lbr.c
  vendor/libspeex/libspeex/hexc_10_32_table.c
  vendor/libspeex/libspeex/hexc_table.c
  vendor/libspeex/libspeex/high_lsp_tables.c
  vendor/libspeex/libspeex/kiss_fft.c
  vendor/libspeex/libspeex/kiss_fftr.c
  vendor/libspeex/libspeex/lpc.c
  vendor/libspeex/libspeex/lsp.c
  vendor/libspeex/libspeex/lsp_tables_nb.c
  vendor/libspeex/libspeex/ltp.c
  vendor/libspeex/libspeex/modes.c
  vendor/libspeex/libspeex/modes_wb.c
  vendor/libspeex/libspeex/nb_celp.c
  vendor/libspeex/libspeex/quant_lsp.c
  vendor/libspeex/libspeex/sb_celp.c
  vendor/libspeex/libspeex/smallft.c
  vendor/libspeex/libspeex/speex.c
  vendor/libspeex/libspeex/speex_callbacks.c
  vendor/libspeex/libspeex/speex_header.c
  vendor/libspeex/libspeex/stereo.c
  vendor/libspeex/libspeex/vbr.c
  vendor/libspeex/libspeex/vorbis_psy.c
  vendor/libspeex/libspeex/vq.c
  vendor/libspeex/libspeex/vq_sse.h
  vendor/libspeex/libspeex/window.c
Labels: enhancement, upstream

#2437 Avoid hierarchy in engineRequestModel function
  Client/mods/deathmatch/logic/CClientModel.cpp
  Client/mods/deathmatch/logic/CClientModelManager.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
Labels: bug

#2438 Add support for WebM files to playSound(3D)
  Client/loader/MainFunctions.cpp
  Client/mods/deathmatch/logic/CClientSoundManager.cpp
  Shared/data/MTA San Andreas/MTA/basswebm.dll
  Shared/data/data files installer.nsi
  Shared/installer/nightly.nsi
Labels: enhancement

#2359 Use vector length method instead of manual distance calculation
  Server/mods/deathmatch/logic/CBuildingRemovalManager.cpp
Labels: refactor
