Repository multitheftauto/mtasa-blue, pull requests merged in 2021-01, with the labels that each got.

#1970 Keep console position and size when changing locale
  Client/core/CGUI.cpp
Labels: bug

#657 setSoundLooped and isSoundLooped functions
  Client/mods/deathmatch/logic/CBassAudio.cpp
  Client/mods/deathmatch/logic/CBassAudio.h
  Client/mods/deathmatch/logic/CClientSound.cpp
  Client/mods/deathmatch/logic/CClientSound.h
  Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.h
Labels: enhancement

#1955 Add transfer box customization
  Client/core/CClientVariables.cpp
  Client/core/CSettings.cpp
  Client/core/CSettings.h
  Client/gui/CGUI_Impl.cpp
  Client/gui/CGUI_Impl.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CResourceFileDownloadManager.cpp
  Client/mods/deathmatch/logic/CResourceFileDownloadManager.h
  Client/mods/deathmatch/logic/CTransferBox.cpp
  Client/mods/deathmatch/logic/CTransferBox.h
  Client/mods/deathmatch/logic/lua/CLuaManager.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaClientDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaClientDefs.h
  Client/mods/deathmatch/logic/rpc/COutputRPCs.cpp
  Client/mods/deathmatch/logic/rpc/COutputRPCs.h
  Client/sdk/gui/CGUI.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CGame.h
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/lua/CLuaManager.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaGenericDefs.h
  Shared/sdk/net/rpc_enums.h
Labels: enhancement

#1986 Fix #521: Network trouble if falling into water while attempting to enter a vehicle
  Client/mods/deathmatch/logic/CClientPed.cpp
Labels: bug

#1915 getElementsWithinRange with interior and dimension check
  Client/mods/deathmatch/StdInc.h
  Client/mods/deathmatch/logic/CClientEntity.cpp
  Client/mods/deathmatch/logic/CClientEntity.h
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
Labels: enhancement

#1982 Add vehicle dependent dummy positions
  Client/game_sa/CAutomobileSA.h
  Client/game_sa/CFxSystemSA.cpp
  Client/game_sa/CFxSystemSA.h
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/game_sa/CPoolsSA.cpp
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/multiplayer_sa/CMultiplayerSA_1.3.cpp
  Client/multiplayer_sa/CMultiplayerSA_VehicleDummies.cpp
  Client/sdk/game/CModelInfo.h
  Client/sdk/game/CVehicle.h
  Client/sdk/game/Common.h
Labels: enhancement

#1991 Update CEF to 87.1.13+g481a82a+chromium-87.0.4280.141
  utils/buildactions/install_cef.lua
Labels: enhancement, upstream

#1995 Enforce existing username length limit
  Server/mods/deathmatch/logic/CAccount.cpp
  Server/mods/deathmatch/logic/CAccountManager.cpp
  Server/mods/deathmatch/logic/CAccountManager.h
Labels: enhancement

#1997 Refactor vehicle blowup
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/CVehicle.cpp
  Server/mods/deathmatch/logic/CVehicle.h
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
Labels: bug

#2006 Add new argument parser to #1999 (Add isBrowserRenderingPaused) and optimize minor things
  Client/cefweb/CWebView.cpp
  Client/cefweb/CWebView.h
  Client/mods/deathmatch/logic/CClientWebBrowser.cpp
  Client/mods/deathmatch/logic/CClientWebBrowser.h
  Client/mods/deathmatch/logic/luadefs/CLuaBrowserDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaBrowserDefs.h
  Client/sdk/core/CWebViewInterface.h
Labels: enhancement

#1908 Add height for colpolygon
  Client/mods/deathmatch/logic/CClientColPolygon.cpp
  Client/mods/deathmatch/logic/CClientColPolygon.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CPacketHandler.h
  Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
  Client/mods/deathmatch/logic/rpc/CColShapeRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CColShapeRPCs.h
  Client/mods/deathmatch/logic/rpc/CElementRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CElementRPCs.h
  Server/mods/deathmatch/logic/CColPolygon.cpp
  Server/mods/deathmatch/logic/CColPolygon.h
  Server/mods/deathmatch/logic/CPerfStat.RPCPacketUsage.cpp
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
  Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp
  Shared/sdk/net/bitstream.h
  Shared/sdk/net/rpc_enums.h
Labels: enhancement

#1651 Fix #995: add onResourceLoadStateChange event
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CResourceManager.cpp
  Server/mods/deathmatch/logic/CResourceManager.h
Labels: enhancement

#1799 Add final where possible - client
  Client/mods/deathmatch/logic/CClientCamera.h
  Client/mods/deathmatch/logic/CClientCivilian.h
  Client/mods/deathmatch/logic/CClientColCircle.h
  Client/mods/deathmatch/logic/CClientColCuboid.h
  Client/mods/deathmatch/logic/CClientColModel.h
  Client/mods/deathmatch/logic/CClientColPolygon.h
  Client/mods/deathmatch/logic/CClientColRectangle.h
  Client/mods/deathmatch/logic/CClientColSphere.h
  Client/mods/deathmatch/logic/CClientColTube.h
  Client/mods/deathmatch/logic/CClientDFF.h
  Client/mods/deathmatch/logic/CClientDummy.h
  Client/mods/deathmatch/logic/CClientEffect.h
  Client/mods/deathmatch/logic/CClientIFP.h
  Client/mods/deathmatch/logic/CClientMarker.h
  Client/mods/deathmatch/logic/CClientPathNode.h
  Client/mods/deathmatch/logic/CClientPickup.h
  Client/mods/deathmatch/logic/CClientPlayer.h
  Client/mods/deathmatch/logic/CClientPointLights.h
  Client/mods/deathmatch/logic/CClientProjectile.h
  Client/mods/deathmatch/logic/CClientRadarArea.h
  Client/mods/deathmatch/logic/CClientRadarMarker.h
  Client/mods/deathmatch/logic/CClientSearchLight.h
  Client/mods/deathmatch/logic/CClientSound.h
  Client/mods/deathmatch/logic/CClientTXD.h
  Client/mods/deathmatch/logic/CClientTeam.h
  Client/mods/deathmatch/logic/CClientWater.h
  Client/mods/deathmatch/logic/CClientWeapon.h
  Client/mods/deathmatch/logic/CDeathmatchObject.h
  Client/mods/deathmatch/logic/CDeathmatchVehicle.h
  Client/mods/deathmatch/logic/CScriptFile.h
  Server/mods/deathmatch/logic/CCustomWeapon.h
  Server/mods/deathmatch/logic/CDatabaseManager.h
Labels: refactor

#2023 Add onClientObjectMoveStart, onClientObjectMoveStop, isObjectMoving
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CDeathmatchObject.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaObjectDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaObjectDefs.h
Labels: enhancement

#2038 Add 6c29e89 to .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: enhancement

#1932 std::monostate support in new parser
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
Labels: enhancement

#2045 Move Linux CI image to multitheftauto namespace
  .github/workflows/build.yaml
  .github/workflows/dockerimage.yaml
  Dockerfile
  vendor/curl/lib/config-linux.h
Labels: enhancement

#2018 Improve shadows by default
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
Labels: enhancement

#2054 Re-order Lua functions defenition to make more sense.
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
Labels: refactor

#2053 Add new "raw" argument fix of #2052
  Server/mods/deathmatch/logic/CResourceHTMLItem.cpp
Labels: enhancement
