Repository multitheftauto/mtasa-blue, pull requests merged in 2021-06, with the labels that each got.

#2198 Potential fix of #1613
  Client/game_sa/CEntitySA.h
  Client/game_sa/CFileLoaderSA.cpp
  Client/game_sa/CFileLoaderSA.h
  Client/game_sa/CGameSA.cpp
  Client/sdk/game/Common.h
Labels: bug

#2246 Update pcre from 8.39 to 8.44
  Shared/mods/deathmatch/logic/luadefs/CLuaUtilDefs.cpp
  vendor/pcre/config.h
  vendor/pcre/config.h.generic
  vendor/pcre/config.h.in
  vendor/pcre/pcre-config.in
  vendor/pcre/pcre.h
  vendor/pcre/pcre.h.in
  vendor/pcre/pcre_compile.c
  vendor/pcre/pcre_dfa_exec.c
  vendor/pcre/pcre_exec.c
  vendor/pcre/pcre_internal.h
  vendor/pcre/pcre_jit_compile.c
  vendor/pcre/pcre_stringpiece.h
  vendor/pcre/pcre_tables.c
  vendor/pcre/pcre_ucd.c
  vendor/pcre/pcrecpp.cc
  vendor/pcre/pcrecpparg.h
  vendor/pcre/pcregrep.c
  vendor/pcre/pcreposix.c
Labels: enhancement, upstream

#2259 Update CEF to 91.1.12+gcf0c26a+chromium-91.0.4472.101
  utils/buildactions/install_cef.lua
Labels: enhancement, upstream

#2250 Refactor of CPlayerManager::IsValidPlayerModel() based on issue #2244
  Server/mods/deathmatch/logic/CPlayerManager.cpp
  Server/mods/deathmatch/logic/CPlayerManager.h
Labels: refactor
