Repository multitheftauto/mtasa-blue, pull requests merged in 2021-03, with the labels that each got.

#2039 Fix #1984 CLuaFunctionRef not working in new parser
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
Labels: bug

#2058 Add on(Client)ElementInteriorChange
  Client/mods/deathmatch/logic/CClientEntity.cpp
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientPed.cpp
  Server/mods/deathmatch/logic/CElement.cpp
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CGame.cpp
Labels: enhancement

#2139 Update CEF to 89.0.12+g2b76680+chromium-89.0.4389.90
  utils/buildactions/install_cef.lua
Labels: enhancement, upstream

#2141 Fix default floor of ColPolygons being zero, rather than max negative
  Client/mods/deathmatch/logic/CClientColPolygon.h
  Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
  Server/mods/deathmatch/logic/CColPolygon.h
  Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
Labels: bug

#2123 Add keybind queue to improve performance
  Client/core/CKeyBinds.cpp
  Client/core/CKeyBinds.h
Labels: enhancement

#2025 Add showCol, isShowCollisionsEnabled, showSound, isShowSoundEnabled for devs
  Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.h
  Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
Labels: enhancement

#2088 Fix #2046: Bone rotating bugs
  Client/game_sa/CEntitySA.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
Labels: bug

#2152 Update Coding Guidelines link on README
  README.md
Labels: documentation, enhancement
