Repository multitheftauto/mtasa-blue, pull requests merged in 2022-04, with the labels that each got.

#2587 Define "HAVE_UNISTD_H" in zlib on Mac systems (#2585)
  vendor/zlib/premake5.lua
Labels: bug

#2584 Update lunasvg from 2.2.0 to 2.3.1
  vendor/lunasvg/README.md
  vendor/lunasvg/include/lunasvg.h
  vendor/lunasvg/source/parser.cpp
Labels: enhancement, upstream

#2499 Remove leftover Discord implementation
  Client/core/CClientVariables.cpp
  Client/core/CConnectManager.cpp
  Client/core/CConnectManager.h
  Client/core/CCore.cpp
  Client/core/CCore.h
  Client/core/CDiscordManager.cpp
  Client/core/CDiscordManager.h
  Client/core/CMainMenu.cpp
  Client/core/CVersionUpdater.cpp
  Client/core/CVersionUpdater.h
  Client/core/DXHook/CDirect3DHook9.cpp
  Client/mods/deathmatch/CClient.cpp
  Client/mods/deathmatch/CClient.h
  Client/mods/deathmatch/StdInc.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CServerInfo.cpp
  Client/mods/deathmatch/logic/rpc/CWorldRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CWorldRPCs.h
  Client/sdk/core/CClientBase.h
  Client/sdk/core/CCoreInterface.h
  Client/sdk/core/CDiscordManagerInterface.h
  Server/mods/deathmatch/StdInc.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CGame.h
  Server/mods/deathmatch/logic/CPacketTranslator.cpp
  Server/mods/deathmatch/logic/CPlayer.h
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaCompatibilityDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.h
  Server/mods/deathmatch/logic/packets/CDiscordJoinPacket.cpp
  Server/mods/deathmatch/logic/packets/CDiscordJoinPacket.h
  Server/mods/deathmatch/logic/packets/CPlayerJoinDataPacket.cpp
  Server/mods/deathmatch/logic/packets/CPlayerJoinDataPacket.h
  Shared/sdk/net/bitstream.h
  premake5.lua
  utils/buildactions/install_discord.lua
Labels: refactor

#2589 Remove async tasks in SVG and update callback usage
  Client/mods/deathmatch/logic/CClientVectorGraphic.cpp
  Client/mods/deathmatch/logic/CClientVectorGraphic.h
  Client/mods/deathmatch/logic/CClientVectorGraphicDisplay.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVectorGraphicDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVectorGraphicDefs.h
Labels: bug

#2558 Fix #2545: isElementInWater in vehicles (client)
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#2506 Add missing chat_text_outline CVAR to getChatboxLayout function
  Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.h
Labels: bug

#2368 Add missing getType method for camera element
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.h
Labels: enhancement

#2449 Variable set relative to false when it has invisible space
  Client/mods/deathmatch/logic/luadefs/CLuaBrowserDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
Labels: enhancement

#2583 Update unrar from 6.02 to 6.11
  vendor/unrar/acknow.txt
  vendor/unrar/archive.cpp
  vendor/unrar/arcread.cpp
  vendor/unrar/cmddata.cpp
  vendor/unrar/cmddata.hpp
  vendor/unrar/cmdfilter.cpp
  vendor/unrar/cmdmix.cpp
  vendor/unrar/consio.cpp
  vendor/unrar/consio.hpp
  vendor/unrar/crc.cpp
  vendor/unrar/encname.cpp
  vendor/unrar/encname.hpp
  vendor/unrar/extract.cpp
  vendor/unrar/file.cpp
  vendor/unrar/file.hpp
  vendor/unrar/filefn.cpp
  vendor/unrar/filefn.hpp
  vendor/unrar/find.cpp
  vendor/unrar/global.cpp
  vendor/unrar/isnt.cpp
  vendor/unrar/isnt.hpp
  vendor/unrar/list.cpp
  vendor/unrar/loclang.hpp
  vendor/unrar/options.hpp
  vendor/unrar/os.hpp
  vendor/unrar/pathfn.cpp
  vendor/unrar/pathfn.hpp
  vendor/unrar/rar.hpp
  vendor/unrar/rdwrfn.cpp
  vendor/unrar/rdwrfn.hpp
  vendor/unrar/recvol5.cpp
  vendor/unrar/rijndael.cpp
  vendor/unrar/rijndael.hpp
  vendor/unrar/rs16.cpp
  vendor/unrar/strfn.cpp
  vendor/unrar/strfn.hpp
  vendor/unrar/timefn.cpp
  vendor/unrar/ui.hpp
  vendor/unrar/uiconsole.cpp
  vendor/unrar/unicode.cpp
  vendor/unrar/unicode.hpp
  vendor/unrar/unpack.hpp
  vendor/unrar/version.hpp
  vendor/unrar/volume.cpp
Labels: enhancement, upstream

#2600 Update json-c from 0.15 to 0.16
  vendor/json-c/ChangeLog
  vendor/json-c/arraylist.c
  vendor/json-c/arraylist.h
  vendor/json-c/config-linux.h
  vendor/json-c/config-macos.h
  vendor/json-c/config-win32.h
  vendor/json-c/debug.h
  vendor/json-c/json_c_version.h
  vendor/json-c/json_object.c
  vendor/json-c/json_object.h
  vendor/json-c/json_object_iterator.c
  vendor/json-c/json_pointer.c
  vendor/json-c/json_tokener.c
  vendor/json-c/json_types.h
  vendor/json-c/json_util.c
  vendor/json-c/linkhash.c
  vendor/json-c/linkhash.h
  vendor/json-c/printbuf.c
  vendor/json-c/printbuf.h
  vendor/json-c/random_seed.c
  vendor/json-c/strerror_override.c
  vendor/json-c/vasprintf_compat.h
Labels: enhancement, upstream
