Repository multitheftauto/mtasa-blue, pull requests merged in 2022-12, with the labels that each got.

#2501 Bugfix: setElementModel reset handling for vehicles created on the server-side
  Client/mods/deathmatch/logic/CClientVehicle.cpp
Labels: bug

#2823 Add CRemoteCall userdata class name 'helper'
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
Labels: enhancement

#2824 Bugfix: setElementModel reset handling for vehicles created on the server-side
  Client/mods/deathmatch/logic/CClientVehicle.cpp
Labels: bug

#1994 Add proper 3D radius check to getElementsWithinRange
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
Labels: enhancement

#2829 "Default" skin remake/upscale (128x128 => 128x256)
  Shared/data/MTA San Andreas/skins/Default/CGUI.is.xml
  Shared/data/MTA San Andreas/skins/Default/CGUI.lnf.xml
  Shared/data/MTA San Andreas/skins/Default/CGUI.png
Labels: enhancement, gui

#2831 Improve CEF DX utilization & thread-safety fixes
  Client/cefweb/CWebView.cpp
  Client/cefweb/CWebView.h
  Client/core/Graphics/CRenderItem.WebBrowser.cpp
Labels: enhancement

#2839 Update nvapi from r510 to r525
  vendor/nvapi/NvApiDriverSettings.c
  vendor/nvapi/NvApiDriverSettings.h
  vendor/nvapi/amd64/nvapi64.lib
  vendor/nvapi/nvHLSLExtns.h
  vendor/nvapi/nvHLSLExtnsInternal.h
  vendor/nvapi/nvShaderExtnEnums.h
  vendor/nvapi/nvapi.h
  vendor/nvapi/nvapi_lite_common.h
  vendor/nvapi/x86/nvapi.lib
Labels: enhancement, upstream

#2838 Update libpng from 1.6.38 to 1.6.39
  vendor/libpng/png.c
  vendor/libpng/png.h
  vendor/libpng/pngconf.h
  vendor/libpng/pngpriv.h
  vendor/libpng/pngread.c
  vendor/libpng/pngrutil.c
  vendor/libpng/pngtest.c
  vendor/libpng/pngwrite.c
  vendor/libpng/pngwutil.c
Labels: enhancement, upstream

#2841 Update zlib from 1.2.12 to 1.2.13
  vendor/libpng/pnglibconf.h
  vendor/zlib/compress.c
  vendor/zlib/crc32.c
  vendor/zlib/deflate.c
  vendor/zlib/deflate.h
  vendor/zlib/gzlib.c
  vendor/zlib/gzread.c
  vendor/zlib/gzwrite.c
  vendor/zlib/infback.c
  vendor/zlib/inflate.c
  vendor/zlib/inftrees.c
  vendor/zlib/inftrees.h
  vendor/zlib/trees.c
  vendor/zlib/uncompr.c
  vendor/zlib/zconf.h
  vendor/zlib/zlib.h
  vendor/zlib/zutil.c
  vendor/zlib/zutil.h
Labels: enhancement, upstream

#2832 SVG related fixes
  Client/mods/deathmatch/logic/CClientVectorGraphicDisplay.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVectorGraphicDefs.cpp
Labels: bug

#2842 Update lunasvg from 2.3.1 to 2.3.5
  vendor/lunasvg/3rdparty/plutovg/FTL.TXT
  vendor/lunasvg/3rdparty/plutovg/plutovg-blend.c
  vendor/lunasvg/3rdparty/plutovg/plutovg-ft-math.c
  vendor/lunasvg/3rdparty/plutovg/plutovg-ft-math.h
  vendor/lunasvg/3rdparty/plutovg/plutovg-ft-raster.c
  vendor/lunasvg/3rdparty/plutovg/plutovg-ft-raster.h
  vendor/lunasvg/3rdparty/plutovg/plutovg-ft-stroker.c
  vendor/lunasvg/3rdparty/plutovg/plutovg-ft-stroker.h
  vendor/lunasvg/3rdparty/plutovg/plutovg-ft-types.h
  vendor/lunasvg/3rdparty/plutovg/plutovg-geometry.c
  vendor/lunasvg/3rdparty/plutovg/plutovg-paint.c
  vendor/lunasvg/3rdparty/plutovg/plutovg-private.h
  vendor/lunasvg/3rdparty/plutovg/plutovg-rle.c
  vendor/lunasvg/3rdparty/plutovg/plutovg.c
  vendor/lunasvg/3rdparty/plutovg/plutovg.h
  vendor/lunasvg/3rdparty/software/sw_ft_math.h
  vendor/lunasvg/3rdparty/software/sw_ft_raster.c
  vendor/lunasvg/3rdparty/software/sw_ft_raster.h
  vendor/lunasvg/3rdparty/software/sw_ft_stroker.h
  vendor/lunasvg/README.md
  vendor/lunasvg/include/export.h
  vendor/lunasvg/include/lunasvg.h
  vendor/lunasvg/premake5.lua
  vendor/lunasvg/source/canvas.cpp
  vendor/lunasvg/source/canvas.h
  vendor/lunasvg/source/clippathelement.cpp
  vendor/lunasvg/source/defselement.cpp
  vendor/lunasvg/source/element.cpp
  vendor/lunasvg/source/element.h
  vendor/lunasvg/source/gelement.cpp
  vendor/lunasvg/source/geometryelement.cpp
  vendor/lunasvg/source/geometryelement.h
  vendor/lunasvg/source/graphicselement.cpp
  vendor/lunasvg/source/graphicselement.h
  vendor/lunasvg/source/layoutcontext.cpp
  vendor/lunasvg/source/layoutcontext.h
  vendor/lunasvg/source/lunasvg.cpp
  vendor/lunasvg/source/markerelement.cpp
  vendor/lunasvg/source/maskelement.cpp
  vendor/lunasvg/source/paintelement.cpp
  vendor/lunasvg/source/paintelement.h
  vendor/lunasvg/source/parser.cpp
  vendor/lunasvg/source/parser.h
  vendor/lunasvg/source/property.cpp
  vendor/lunasvg/source/property.h
  vendor/lunasvg/source/stopelement.cpp
  vendor/lunasvg/source/styledelement.cpp
  vendor/lunasvg/source/styledelement.h
  vendor/lunasvg/source/styleelement.cpp
  vendor/lunasvg/source/svgelement.cpp
  vendor/lunasvg/source/svgelement.h
  vendor/lunasvg/source/symbolelement.cpp
  vendor/lunasvg/source/useelement.cpp
Labels: enhancement, upstream

#2849 Possible crash fix for libcef(0x3705563)
  Client/cefweb/CWebApp.cpp
Labels: bug

#2215 Add set/getChatboxCharacterLimit and increase max chat message length to 255
  Client/core/CChat.cpp
  Client/core/CChat.h
  Client/core/CCore.cpp
  Client/core/CCore.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/Config.h
  Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.h
  Client/sdk/core/CCoreInterface.h
  Server/mods/deathmatch/Config.h
Labels: enhancement

#2830 Add a new upscaled/remade "Default New" skin as a replica (128x128 -> 128x258)
  Client/core/CGUI.cpp
  Shared/data/MTA San Andreas/skins/Default 2023/CGUI.is.xml
  Shared/data/MTA San Andreas/skins/Default 2023/CGUI.lnf.xml
  Shared/data/MTA San Andreas/skins/Default 2023/CGUI.png
  Shared/data/MTA San Andreas/skins/Default 2023/CGUI.xml
  Shared/data/data files installer.nsi
  Shared/installer/nightly.nsi
Labels: enhancement, gui

#2853 Fix ped duplication issue introduced in #2828
  Client/game_sa/CPedSA.cpp
Labels: bug
