Repository multitheftauto/mtasa-blue, pull requests merged in 2022-01, with the labels that each got.

#2494 Fix chatbox when using recently added inputBlocked argument
  Client/core/CChat.cpp
Labels: bug

#2354 Fix #2349 (Interiors lack radio)
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/sdk/multiplayer/CMultiplayer.h
Labels: bug

#2474 Fix object stream
  Client/mods/deathmatch/logic/CClientObject.cpp
Labels: bug

#2486 Fix crash when pickup has invalid custom model
  Client/mods/deathmatch/logic/CClientModel.cpp
Labels: bug

#2073 Add tab panel into Audio tab
  Client/core/CSettings.cpp
  Client/core/CSettings.h
Labels: enhancement

#2487 Fix healthbar blinking faster on high fps
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: bug

#2495 Add new world special property (vehicle sun glare effect)
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
Labels: enhancement

#2527 Fix sun glare effect still enabled when join to other server (PR 2526)
  Client/game_sa/CGameSA.cpp
Labels: bug

#2530 Refactor & fixed the code wording of PR 2526
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
Labels: refactor
