Repository multitheftauto/mtasa-blue, pull requests merged in 2022-09, with the labels that each got.

#2706 Improve performance of CClientObjectManager::UpdateLimitInfo
  Client/mods/deathmatch/logic/CClientObjectManager.cpp
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/multiplayer_sa/CMultiplayerSA_ObjectStreamerOptimization.cpp
  Client/sdk/multiplayer/CMultiplayer.h
Labels: enhancement

#2682 Change max fpslimit to 500
  Client/core/CClientVariables.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CMainConfig.cpp
Labels: enhancement

#2708 Add isCapsLockEnabled client function
  Client/mods/deathmatch/logic/luadefs/CLuaClientDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaClientDefs.h
Labels: enhancement

#2679 Fix #2677: MTA does not render grass correctly
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: bug

#2592 Add missing model ids and names scraped from .ide files
  Client/mods/deathmatch/logic/CModelNames.cpp
Labels: enhancement

#961 Fix #948: cancelEvent works onElementModelChange
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#1779 Allow allocating new timed-object models using engineRequestModel
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientModel.cpp
  Client/mods/deathmatch/logic/CClientModel.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/sdk/game/CModelInfo.h
Labels: enhancement

#2645 Fix disappearing of server browser search input
  Client/core/ServerBrowser/CServerBrowser.cpp
Labels: bug

#1828 Refactor CBufferRef to use shared_ptr
  Shared/mods/deathmatch/logic/CLatentSendQueue.cpp
  Shared/mods/deathmatch/logic/CLatentTransferManager.cpp
  Shared/mods/deathmatch/logic/CLatentTransferManager.h
Labels: refactor

#1825 Remove CRefCountableST
  Client/mods/deathmatch/logic/CClientEntity.cpp
  Client/mods/deathmatch/logic/CClientEntity.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/rpc/CElementRPCs.cpp
  Server/mods/deathmatch/logic/CElement.cpp
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Shared/sdk/SharedUtil.Misc.h
Labels: enhancement

#2529 Add new world special property (corona ztest)
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
Labels: enhancement

#2371 Add isMTAWindowFocused() and onClientMTAFocusChange
  Client/core/CMessageLoopHook.cpp
  Client/mods/deathmatch/CClient.cpp
  Client/mods/deathmatch/CClient.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/luadefs/CLuaClientDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaClientDefs.h
  Client/sdk/core/CClientBase.h
Labels: enhancement

#2713 Clear script memory after it has been loaded
  Client/mods/deathmatch/logic/CResource.cpp
  Client/mods/deathmatch/logic/lua/CLuaMain.cpp
  Shared/sdk/SharedUtil.Buffer.h
Labels: enhancement

#2552 Improve setSoundEffectParameters error messages
  Client/mods/deathmatch/logic/CBassAudio.cpp
  Client/mods/deathmatch/logic/CBassAudio.h
  Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.cpp
Labels: enhancement, stale

#2739 Do not display forbidden programs message on custom builds
  Client/loader/Main.cpp
Labels: enhancement

#2738 Move Lua code to wiki
  Client/game_sa/CWeaponStatManagerSA.cpp
  Server/mods/deathmatch/logic/CWeaponStatManager.cpp
Labels: refactor

#2744 Skip "Are you having problems running MTA" message on custom builds
  Client/loader/MainFunctions.cpp
Labels: enhancement

#2761 GameSA cleanup #1
  Client/game_sa/CCarGeneratorSA.cpp
  Client/game_sa/CCarGeneratorSA.h
  Client/game_sa/CFontSA.cpp
  Client/game_sa/CFontSA.h
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CHudSA.cpp
  Client/game_sa/CHudSA.h
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/game_sa/CRemoteSA.cpp
  Client/game_sa/CRemoteSA.h
  Client/game_sa/CRestartSA.cpp
  Client/game_sa/CRestartSA.h
  Client/game_sa/CTheCarGeneratorsSA.cpp
  Client/game_sa/CTheCarGeneratorsSA.h
  Client/game_sa/CWantedSA.cpp
  Client/game_sa/CWantedSA.h
  Client/game_sa/CWorldSA.cpp
  Client/game_sa/CWorldSA.h
  Client/game_sa/StdInc.h
  Client/sdk/game/CCarGenerator.h
  Client/sdk/game/CFont.h
  Client/sdk/game/CGame.h
  Client/sdk/game/CHud.h
  Client/sdk/game/CModelInfo.h
  Client/sdk/game/CRemote.h
  Client/sdk/game/CRestart.h
  Client/sdk/game/CTheCarGenerators.h
  Client/sdk/game/CWanted.h
  Client/sdk/game/CWorld.h
Labels: refactor

#2496 HMAC Support
  Shared/mods/deathmatch/logic/Enums.cpp
  Shared/mods/deathmatch/logic/Enums.h
  Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.h
  Shared/sdk/SharedUtil.Crypto.h
  Shared/sdk/SharedUtil.Hash.h
  Shared/sdk/SharedUtil.Tests.hpp
Labels: enhancement

#2764 Clean up game_sa project round 2
  Client/game_sa/CCivilianPedSA.cpp
  Client/game_sa/CEntitySA.cpp
  Client/game_sa/CEntitySA.h
  Client/game_sa/CEventGroupSA.cpp
  Client/game_sa/CEventGroupSA.h
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CHandlingManagerSA.cpp
  Client/game_sa/CMenuManagerSA.cpp
  Client/game_sa/CMenuManagerSA.h
  Client/game_sa/CObjectSA.cpp
  Client/game_sa/COffsets.cpp
  Client/game_sa/COffsets.h
  Client/game_sa/CParticleObjectSA.cpp
  Client/game_sa/CParticleObjectSA.h
  Client/game_sa/CParticleSA.cpp
  Client/game_sa/CParticleSA.h
  Client/game_sa/CParticleSystemManagerSA.cpp
  Client/game_sa/CParticleSystemManagerSA.h
  Client/game_sa/CPedIntelligenceSA.cpp
  Client/game_sa/CPedIntelligenceSA.h
  Client/game_sa/CPlayerInfoSA.cpp
  Client/game_sa/CPlayerInfoSA.h
  Client/game_sa/CPlayerPedSA.cpp
  Client/game_sa/CPopulationSA.cpp
  Client/game_sa/CPopulationSA.h
  Client/game_sa/CTaskManagementSystemSA.cpp
  Client/game_sa/CTaskManagementSystemSA.h
  Client/game_sa/CTaskManagerSA.cpp
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleScannerSA.cpp
  Client/game_sa/CVehicleScannerSA.h
  Client/game_sa/StdInc.h
  Client/game_sa/TaskIKSA.cpp
  Client/game_sa/TaskSA.cpp
  Client/sdk/game/CEventGroup.h
  Client/sdk/game/CGame.h
  Client/sdk/game/CMenuManager.h
  Client/sdk/game/CParticle.h
  Client/sdk/game/CParticleObject.h
  Client/sdk/game/CParticleSystemManager.h
  Client/sdk/game/CPedIntelligence.h
  Client/sdk/game/CPlayerInfo.h
  Client/sdk/game/CPopulation.h
  Client/sdk/game/CTaskManagementSystem.h
  Client/sdk/game/CVehicleScanner.h
Labels: refactor

#2743 Recalculate frame rate limit on fps_limit cvar change
  Client/core/CCommands.cpp
  Client/core/CCommands.h
Labels: enhancement

#2768 Clean up game_sa project round 3
  Client/game_sa/C3DMarkerSA.h
  Client/game_sa/C3DMarkersSA.cpp
  Client/game_sa/C3DMarkersSA.h
  Client/game_sa/CAutomobileSA.cpp
  Client/game_sa/CAutomobileSA.h
  Client/game_sa/COffsets.cpp
  Client/game_sa/CPathFindSA.cpp
  Client/game_sa/CPathFindSA.h
  Client/game_sa/CPlayerInfoSA.cpp
  Client/game_sa/CPlayerInfoSA.h
  Client/game_sa/CPlayerPedSA.cpp
  Client/game_sa/CRadarSA.cpp
  Client/game_sa/CRadarSA.h
  Client/game_sa/CStatsSA.cpp
  Client/game_sa/CStatsSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
  Client/game_sa/CWeatherSA.cpp
  Client/game_sa/CWeatherSA.h
  Client/sdk/game/CAutomobile.h
  Client/sdk/game/CPathFind.h
  Client/sdk/game/CPlayerInfo.h
  Client/sdk/game/CRadar.h
  Client/sdk/game/CStats.h
  Client/sdk/game/CVehicle.h
  Client/sdk/game/CWeather.h
Labels: refactor

#2771 Clean up game_sa project round 4
  Client/game_sa/CCivilianPedSA.cpp
  Client/game_sa/CCivilianPedSA.h
  Client/game_sa/CPedSA.cpp
  Client/game_sa/CPedSA.h
  Client/game_sa/CPoolsSA.cpp
  Client/game_sa/CPoolsSA.h
  Client/game_sa/StdInc.h
  Client/mods/deathmatch/logic/CClientCivilian.cpp
  Client/mods/deathmatch/logic/CClientCivilian.h
  Client/mods/deathmatch/logic/CClientCivilianManager.cpp
  Client/mods/deathmatch/logic/CClientCivilianManager.h
  Client/mods/deathmatch/logic/CClientEntity.h
  Client/mods/deathmatch/logic/CClientManager.cpp
  Client/mods/deathmatch/logic/CClientManager.h
  Client/mods/deathmatch/logic/CClientPed.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/multiplayer_sa/CPopulationSA.cpp
  Client/multiplayer_sa/CPopulationSA.h
  Client/multiplayer_sa/StdInc.h
  Client/sdk/game/CCivilianPed.h
  Client/sdk/game/CPed.h
  Client/sdk/game/CPools.h
  Client/sdk/multiplayer/CMultiplayer.h
  Client/sdk/multiplayer/CPopulationMP.h
Labels: refactor
