Repository multitheftauto/mtasa-blue, pull requests merged in 2023-07, with the labels that each got.

#3086 Functions to control the streaming memory/buffer sizes [Fixes #3084]
  Client/core/CCore.cpp
  Client/core/CCore.h
  Client/core/CMemStats.cpp
  Client/core/CMemStats.h
  Client/game_sa/CStreamingSA.cpp
  Client/game_sa/CStreamingSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/CClientIMG.cpp
  Client/mods/deathmatch/logic/CClientIMG.h
  Client/mods/deathmatch/logic/CClientIMGManager.cpp
  Client/mods/deathmatch/logic/CClientIMGManager.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/sdk/core/CCoreInterface.h
Labels: bug, enhancement

#3089 Fix #3088: Resolve cursor being invisible with main menu open in certain scenarios
  Client/core/CGUI.cpp
  Client/core/CMainMenu.cpp
  Client/core/CMainMenu.h
Labels: bug

#3042 Fix #3037: Add ResetPedVoice function
  Client/game_sa/CPedSA.cpp
  Client/game_sa/CPedSA.h
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CClientPed.h
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
  Client/sdk/game/CPed.h
Labels: enhancement

#2999 Refactor few functions in CLuaCameraDefs to use new parser
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.h
Labels: refactor

#2114 Detect integral underflow, NaN and inf values in the new parser
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
  Shared/mods/deathmatch/logic/lua/LuaBasic.cpp
Labels: enhancement

#2130 Add support for class methods in new argument parser
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
Labels: enhancement

#3110 Fix CStreamingSA::GetUnusedStreamHandle
  Client/game_sa/CStreamingSA.cpp
Labels: bug

#3111 IMG count extension
  Client/game_sa/CStreamingSA.cpp
  Client/game_sa/CStreamingSA.h
  Client/mods/deathmatch/logic/CClientIMG.cpp
  Client/sdk/game/CStreaming.h
Labels: enhancement

#2422 Add grain effect functions
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.h
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/multiplayer_sa/CMultiplayerSA_Postprocess.cpp
  Client/sdk/multiplayer/CMultiplayer.h
Labels: enhancement

#2991 Move cluatimer to shared folder
  Client/mods/deathmatch/logic/lua/CLuaTimer.cpp
  Client/mods/deathmatch/logic/lua/CLuaTimer.h
  Client/mods/deathmatch/logic/lua/CLuaTimerManager.h
  Server/mods/deathmatch/logic/lua/CLuaTimerManager.h
  Shared/mods/deathmatch/logic/lua/CLuaTimer.cpp
  Shared/mods/deathmatch/logic/lua/CLuaTimer.h
Labels: refactor

#1820 Use CCustomData by value in CElement instead of a pointer
  Server/mods/deathmatch/logic/CElement.cpp
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp
Labels: refactor

#2369 Add new glitch (don't burn flipped cars)
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/sdk/multiplayer/CMultiplayer.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CGame.h
  Server/mods/deathmatch/logic/packets/CMapInfoPacket.cpp
  Shared/sdk/net/SyncStructures.h
  Shared/sdk/net/bitstream.h
Labels: enhancement, feedback

#3046 Add SA credits
  Client/core/CCredits.cpp
  Client/core/CCredits.h
Labels: enhancement

#3010 Fix #1166: Allow getCursorPosition if console or chat input is open
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#3131 Allow allocating clump models
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientModel.cpp
  Client/mods/deathmatch/logic/CClientModel.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/sdk/game/CModelInfo.h
Labels: enhancement

#3036 Render cursor in current frame
  Client/gui/CGUI_Impl.cpp
Labels: enhancement

#3130 Add onExplosion event
  Server/mods/deathmatch/logic/CGame.cpp
Labels: enhancement
