Repository multitheftauto/mtasa-blue, pull requests merged in 2023-08, with the labels that each got.

#3112 Fix a desync state after aborted carjacking
  Client/mods/deathmatch/logic/CPacketHandler.cpp
Labels: bug

#3033 Add new world special property (water creatures)
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
Labels: enhancement

#3146 Fix #3143: Ped revives when syncer changes
  Server/mods/deathmatch/logic/CGame.cpp
Labels: bug

#3145 Add fileGetContents function to server and client
  Client/mods/deathmatch/logic/CResource.cpp
  Client/mods/deathmatch/logic/CResource.h
  Client/mods/deathmatch/logic/CScriptFile.cpp
  Client/mods/deathmatch/logic/CScriptFile.h
  Server/mods/deathmatch/logic/CResource.cpp
  Server/mods/deathmatch/logic/CResource.h
  Server/mods/deathmatch/logic/CScriptFile.cpp
  Server/mods/deathmatch/logic/CScriptFile.h
  Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.h
Labels: enhancement

#2976 dxCreateRenderTarget custom surface format
  Client/core/CChat.cpp
  Client/core/CScreenGrabber.cpp
  Client/core/Graphics/CGraphics.cpp
  Client/core/Graphics/CRenderItem.RenderTarget.cpp
  Client/core/Graphics/CRenderItemManager.cpp
  Client/core/Graphics/CRenderItemManager.h
  Client/mods/deathmatch/logic/CClientRenderElementManager.cpp
  Client/mods/deathmatch/logic/CClientRenderElementManager.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Client/sdk/core/CRenderItemManagerInterface.h
Labels: enhancement

#3116 Add function `engineStreamingSetModelCacheLimits`
  Client/core/CModelCacheManager.cpp
  Client/core/CModelCacheManager.h
  Client/mods/deathmatch/logic/CClientModelCacheManager.cpp
  Client/mods/deathmatch/logic/CClientModelCacheManager.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
Labels: enhancement

#3099 Add texture hit info to `processLineOfSight`
  Client/game_sa/CColModelSA.h
  Client/game_sa/CCollisionSA.cpp
  Client/game_sa/CCollisionSA.h
  Client/game_sa/CRenderWareSA.cpp
  Client/game_sa/CWorldSA.cpp
  Client/game_sa/CWorldSA.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Client/sdk/game/CCollision.h
  Client/sdk/game/CWorld.h
  Client/sdk/game/RenderWare.h
  Shared/sdk/CVector.h
Labels: enhancement

#3040 Fix #2963: Add support for double click events in CEF
  Client/cefweb/CWebView.cpp
  Client/cefweb/CWebView.h
  Client/gui/CGUIWebBrowser_Impl.cpp
  Client/gui/CGUIWebBrowser_Impl.h
  Client/mods/deathmatch/logic/CClientWebBrowser.cpp
  Client/mods/deathmatch/logic/CClientWebBrowser.h
  Client/mods/deathmatch/logic/luadefs/CLuaBrowserDefs.cpp
  Client/sdk/core/CWebViewInterface.h
Labels: bug

#2992 Add rustlerbombs and speedometer to default startup resources
  Server/mods/deathmatch/mtaserver.conf
Labels: enhancement

#2535 Add getColorFilter
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.h
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/sdk/multiplayer/CMultiplayer.h
Labels: enhancement

#3120 Additional API to change model TXD
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
  Client/sdk/game/CModelInfo.h
Labels: enhancement

#1802 Allow allocating new TXD's
  Client/game_sa/CGameSA.h
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CPoolsSA.cpp
  Client/game_sa/CPoolsSA.h
  Client/game_sa/CTextureDictonarySA.h
  Client/mods/deathmatch/logic/CClientModel.cpp
  Client/mods/deathmatch/logic/CClientModel.h
  Client/mods/deathmatch/logic/CClientModelManager.cpp
  Client/mods/deathmatch/logic/CClientModelManager.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
  Client/sdk/game/CPools.h
Labels: enhancement, feedback
