Repository multitheftauto/mtasa-blue, pull requests merged in 2023-06, with the labels that each got.

#3063 Fix missing file close call during IMG unloading
  Client/mods/deathmatch/logic/CClientIMG.cpp
Labels: bug

#3023 Raise default fps limit to 74
  Server/mods/deathmatch/editor.conf
  Server/mods/deathmatch/local.conf
  Server/mods/deathmatch/mtaserver.conf
Labels: enhancement

#3034 Fix #2944: Fix cursor alpha issues
  Client/core/CGUI.cpp
  Client/core/CMessageLoopHook.cpp
  Client/gui/CGUI_Impl.cpp
  Client/gui/CGUI_Impl.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/sdk/gui/CGUI.h
Labels: bug

#3064 Update credits
  Client/core/CCredits.cpp
  Shared/data/MTA San Andreas/MTA/locale/en_US/client.pot
Labels: enhancement, documentation

#3030 Entity cleanup
  Client/mods/deathmatch/logic/CClientEntity.h
Labels: refactor
