Repository multitheftauto/mtasa-blue, pull requests merged in 2023-05, with the labels that each got.

#2986 Remove lua_makestring unused function
  Client/mods/deathmatch/logic/lua/LuaCommon.cpp
  Client/mods/deathmatch/logic/lua/LuaCommon.h
  Server/mods/deathmatch/logic/lua/LuaCommon.cpp
  Server/mods/deathmatch/logic/lua/LuaCommon.h
Labels: refactor

#2974 Fix for issue #2973
  Client/core/Graphics/CTileBatcher.cpp
Labels: bug

#2940 Fix #2386: Crash fix
  Shared/mods/deathmatch/logic/CLatentReceiver.cpp
  Shared/mods/deathmatch/logic/CLatentTransferManager.cpp
  Shared/mods/deathmatch/logic/CLatentTransferManager.h
Labels: bug

#2929 Add ability to get debug setting in dxGetStatus
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
Labels: enhancement

#2925 Add persist parameter to setElementSyncer
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CObjectSync.cpp
  Server/mods/deathmatch/logic/CObjectSync.h
  Server/mods/deathmatch/logic/CPedSync.cpp
  Server/mods/deathmatch/logic/CPedSync.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/CUnoccupiedVehicleSync.cpp
  Server/mods/deathmatch/logic/CUnoccupiedVehicleSync.h
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
Labels: enhancement

#2143 Refactor WriteStringCharacters and WriteString in BitStream to use string_view
  Client/game_sa/StdInc.h
  Client/multiplayer_sa/StdInc.h
  Server/mods/deathmatch/logic/packets/CConsoleEchoPacket.cpp
  Server/mods/deathmatch/logic/packets/CDebugEchoPacket.cpp
  Server/mods/deathmatch/logic/packets/CLuaEventPacket.cpp
  Server/mods/deathmatch/logic/packets/CPlayerChangeNickPacket.cpp
  Shared/sdk/net/bitstream.h
Labels: refactor

#1631 Rename set/getCameraShakeLevel to set/getCameraDrunkLevel
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.h
  Client/mods/deathmatch/logic/luadefs/CLuaCompatibilityDefs.cpp
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
Labels: enhancement

#2920 Fix #2906: warpPedIntoVehicle causes a C++ runtime assertion failure
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CVehicle.cpp
Labels: bug

#3013 Remove some strange undocumented logic from `Client/core/CCommandFuncs.cpp`
  Client/core/CCommandFuncs.cpp
Labels: refactor

#3016 Fix #3015, ignore empty string in executeBrowserJavascript
  Client/mods/deathmatch/logic/luadefs/CLuaBrowserDefs.cpp
Labels: bug

#3018 Feature: Refactor UTF defs to use new lua parser
  Shared/mods/deathmatch/logic/luadefs/CLuaUTFDefs.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaUTFDefs.h
Labels: refactor

#3017 Fix #418, addCommandHandler: Returning False for Existing Built-in Commands
  Client/mods/deathmatch/logic/CRegisteredCommands.cpp
  Server/mods/deathmatch/logic/CMainConfig.cpp
  Server/mods/deathmatch/logic/CMainConfig.h
  Server/mods/deathmatch/logic/CRegisteredCommands.cpp
Labels: bug

#3021 Fix #2922
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bug

#2995 Fix ase description default value in mtaserver.conf and mtaserver.conf.template
  Server/mods/deathmatch/mtaserver.conf
  Server/mods/deathmatch/mtaserver.conf.template
Labels: bug, documentation

#2997 Remove whitespaces surrounding some tags
  Server/mods/deathmatch/editor.conf
  Server/mods/deathmatch/local.conf
  Server/mods/deathmatch/mtaserver.conf
  Server/mods/deathmatch/mtaserver.conf.template
Labels: bug
