Repository multitheftauto/mtasa-blue, pull requests merged in 2023-04, with the labels that each got.

#2846 Update credits
  Client/core/CCredits.cpp
  Shared/data/MTA San Andreas/MTA/locale/en_US/client.pot
Labels: enhancement, documentation

#2914 Correct Visual Studio studio version in Readme
  README.md
Labels: feedback, documentation

#1612 Fix #1474: Implement getAllElementData client-side
  Client/mods/deathmatch/logic/CClientEntity.cpp
  Client/mods/deathmatch/logic/CClientEntity.h
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
  Server/mods/deathmatch/logic/CElement.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
  Shared/mods/deathmatch/logic/luadefs/CLuaElementDefsShared.cpp
Labels: enhancement

#2032 Allow multiple ignored elements to be passed to processLineOfSight
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
Labels: enhancement

#2084 Improve player sync when exiting vehicle
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CNetAPI.cpp
  Client/mods/deathmatch/logic/CUnoccupiedVehicleSync.cpp
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CUnoccupiedVehicleSync.cpp
  Server/mods/deathmatch/logic/net/CSimPlayer.h
  Server/mods/deathmatch/logic/net/CSimPlayerManager.cpp
Labels: enhancement, backwards-incompatible

#2655 Fix #2654: Uncap money serverside
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: enhancement

#2678 Fix random foliage on replaced collisions
  Client/game_sa/CModelInfoSA.cpp
Labels: bug

#2746 Disable camera collisions for detached vehicle parts and projectiles
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: enhancement

#2808 Add missing special skins
  Client/game_sa/CGameSA.cpp
  Client/mods/deathmatch/logic/CClientModelCacheManager.cpp
  Server/mods/deathmatch/logic/CPlayerManager.cpp
Labels: enhancement

#2934 Fix #2917: Fix Get/Set vehicle model wheel size memory leak
  Client/game_sa/CModelInfoSA.cpp
Labels: bug

#2765 Use MTA screenshot function for photos taken by in-game camera weapon
  Client/core/CCommandFuncs.cpp
  Client/core/CCore.cpp
  Client/core/CCore.h
  Client/core/CScreenShot.cpp
  Client/core/CScreenShot.h
  Client/core/DXHook/CDirect3DEvents9.cpp
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/sdk/core/CCoreInterface.h
Labels: enhancement

#2866 Allow unload model with custom col
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
Labels: bug, refactor

#1714 Add interface for model flags
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
  Client/multiplayer_sa/CMultiplayerSA_CrashFixHacks.cpp
  Client/sdk/game/CGame.h
  Client/sdk/game/CModelInfo.h
Labels: enhancement

#2180 Use int instead of size_t as index in CLuaFunctionParser as it use negative indices
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
  Shared/mods/deathmatch/logic/lua/LuaBasic.cpp
  Shared/mods/deathmatch/logic/lua/LuaBasic.h
Labels: refactor

#2144 Add a few functions to SFixedString
  Shared/sdk/SharedUtil.Misc.h
Labels: enhancement

#2095 Implement ped far sync interval
  Server/mods/deathmatch/editor.conf
  Server/mods/deathmatch/local.conf
  Server/mods/deathmatch/logic/CMainConfig.cpp
  Server/mods/deathmatch/logic/CPed.cpp
  Server/mods/deathmatch/logic/CPed.h
  Server/mods/deathmatch/logic/CPedSync.cpp
  Server/mods/deathmatch/logic/CPedSync.h
  Server/mods/deathmatch/logic/packets/CPedSyncPacket.cpp
  Server/mods/deathmatch/logic/packets/CPedSyncPacket.h
  Server/mods/deathmatch/mtaserver.conf
  Server/mods/deathmatch/mtaserver.conf.template
  Shared/mods/deathmatch/logic/CTickRateSettings.h
Labels: enhancement

#2950 Fix collision streaming regression from #1714
  Client/game_sa/CModelInfoSA.cpp
Labels: bug

#2953 Fix engineResetModelFlags argument parsing
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
Labels: bug

#2955 Fix #2774: Prevent kick during redirect
  Server/mods/deathmatch/logic/CPlayer.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
Labels: bug

#2962 Tweak 'Visit news' button to fit the localized string
  Client/core/CNewsBrowser.cpp
Labels: bug, i18n/l10n

#2964 Addendum to 1c00ef9b - fix crash happening on debug builds
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: bug
