Repository multitheftauto/mtasa-blue, pull requests merged in 2023-09, with the labels that each got.

#3161 Add serverside is/setWorldSpecialProperty (includes new property "burnflippedcars")
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.h
  Client/mods/deathmatch/logic/rpc/CWorldRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CWorldRPCs.h
  Client/sdk/game/CGame.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CGame.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaWorldDefs.h
  Server/mods/deathmatch/logic/packets/CMapInfoPacket.cpp
  Shared/mods/deathmatch/logic/Enums.cpp
  Shared/mods/deathmatch/logic/Enums.h
  Shared/sdk/net/SyncStructures.h
  Shared/sdk/net/bitstream.h
  Shared/sdk/net/rpc_enums.h
Labels: enhancement

#3179 Add new world special property (fireballdestruct)
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/sdk/game/CGame.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/packets/CMapInfoPacket.cpp
  Shared/mods/deathmatch/logic/Enums.cpp
  Shared/mods/deathmatch/logic/Enums.h
  Shared/sdk/net/SyncStructures.h
  Shared/sdk/net/bitstream.h
Labels: enhancement

#1935 Implement #1916: Make client-side setVehicleHandling to work on vehicles created server-side
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: enhancement, sync

#3171 Fix Unicode file path passed in CClientIMG
  Client/game_sa/CStreamingSA.cpp
  Client/game_sa/CStreamingSA.h
  Client/mods/deathmatch/logic/CClientIMG.cpp
  Client/mods/deathmatch/logic/CClientIMG.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/sdk/game/CStreaming.h
Labels: bug

#3092 Workaround Fix #1326: Screen flickering on high memory usage
  Client/multiplayer_sa/CMultiplayerSA_Rendering.cpp
Labels: bug

#3059 Fix replacing markers
  Client/game_sa/C3DMarkersSA.cpp
  Client/game_sa/C3DMarkersSA.h
  Client/mods/deathmatch/logic/CClientDFF.cpp
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/CClientMarkerManager.cpp
  Client/mods/deathmatch/logic/CClientMarkerManager.h
  Client/sdk/game/C3DMarkers.h
Labels: enhancement

#3194 Fix assert when model info is missing
  Client/game_sa/CModelInfoSA.cpp
Labels: regression

#3195 Fix engineFreeModel crashes
  Client/mods/deathmatch/logic/CClientModel.cpp
  Client/mods/deathmatch/logic/CClientModel.h
  Client/mods/deathmatch/logic/CClientModelManager.cpp
Labels: regression
