Repository multitheftauto/mtasa-blue, pull requests merged in 2024-07, with the labels that each got.

#3525 Fix #1181 setPedWeaponSlot doesn't update data
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bugfix

#3565 Fix removeWorldModel crash
  Client/game_sa/CBuildingRemovalSA.cpp
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/sdk/game/CGame.h
Labels: bugfix

#3562 Fix #1757 extinguishFire in onClientVehicleDamage causes MTA crash
  Client/multiplayer_sa/CMultiplayerSA_CrashFixHacks.cpp
Labels: bugfix

#3482 Optimization Handling
  Client/game_sa/CHandlingManagerSA.cpp
  Client/game_sa/CHandlingManagerSA.h
  Client/sdk/game/CHandlingManager.h
  Client/sdk/game/Common.h
  Server/mods/deathmatch/logic/CHandlingManager.cpp
  Server/mods/deathmatch/logic/CHandlingManager.h
Labels: refactor

#3559 Fix #508 Texture bug with setJetpackWeaponEnabled
  Client/multiplayer_sa/CMultiplayerSA_1.3.cpp
Labels: bugfix

#3553 Fix outputDebugString level 4 not being logged
  Client/mods/deathmatch/logic/CScriptDebugging.cpp
  Client/mods/deathmatch/logic/CScriptDebugging.h
  Server/mods/deathmatch/logic/CScriptDebugging.cpp
  Shared/mods/deathmatch/logic/CScriptDebugging.cpp
Labels: bugfix

#3550 Checkpoints arrow customization
  Client/game_sa/CCheckpointSA.cpp
  Client/game_sa/CCheckpointSA.h
  Client/game_sa/CCheckpointsSA.cpp
  Client/game_sa/CCheckpointsSA.h
  Client/game_sa/CGameSA.cpp
  Client/mods/deathmatch/logic/CClientCheckpoint.cpp
  Client/mods/deathmatch/logic/CClientCheckpoint.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaMarkerDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaMarkerDefs.h
  Client/mods/deathmatch/logic/rpc/CMarkerRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CMarkerRPCs.h
  Client/sdk/game/CCheckpoint.h
  Client/sdk/game/CCheckpoints.h
  Server/mods/deathmatch/logic/CMarker.cpp
  Server/mods/deathmatch/logic/CMarker.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaMarkerDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaMarkerDefs.h
  Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp
  Shared/sdk/net/bitstream.h
  Shared/sdk/net/rpc_enums.h
Labels: enhancement

#3533 Fix #624 & 3532 onClientObjectBreak has attacker=nil when broken object is glass
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: bugfix

#3534 GetPlayerScriptDebugLevel OOP syntax unification
  Client/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
Labels: refactor

#3531 GetResourceName default parameter and Global variable
  Client/mods/deathmatch/logic/lua/CLuaMain.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaResourceDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaResourceDefs.h
  Server/mods/deathmatch/logic/lua/CLuaMain.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaResourceDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaResourceDefs.h
Labels: enhancement

#3574 Appendum - CLuaFunctionParser refactor (#3494)
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
Labels: refactor

#3613 Fix #3612 Explosions breaking glass cause crash
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: bugfix

#3616 Appendum #3585 - shakeCamera
  Client/game_sa/CCameraSA.cpp
  Client/game_sa/CCameraSA.h
  Client/mods/deathmatch/logic/CClientCamera.cpp
  Client/mods/deathmatch/logic/CClientCamera.h
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.h
  Client/sdk/game/CCamera.h
Labels: enhancement

#3513 Fix building LOD's crash
  Client/mods/deathmatch/logic/CClientBuilding.cpp
  Client/mods/deathmatch/logic/CClientBuildingManager.cpp
Labels: bugfix

#2855 Tweak mouse cursor startup behaviour
  Client/core/CCore.cpp
  Client/core/CCore.h
  Client/core/CGUI.cpp
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: enhancement

#2554 Add new onClientCoreCommand event
  Client/core/CCommands.cpp
  Client/mods/deathmatch/ClientCommands.cpp
  Client/mods/deathmatch/ClientCommands.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/sdk/core/CCommandsInterface.h
Labels: enhancement, feedback

#2566 Add getVehicleEntryPoints
  Client/game_sa/CCarEnterExitSA.cpp
  Client/game_sa/CCarEnterExitSA.h
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Client/sdk/game/CCarEnterExit.h
Labels: enhancement, feedback

#3177 Fix #2852: add optional 'property' parameter to getVehicleHandling function
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaHandlingDefs.cpp
Labels: enhancement
