Repository multitheftauto/mtasa-blue, pull requests merged in 2024-09, with the labels that each got.

#3690 Fix bad destructor for buildings
  Client/game_sa/CBuildingsPoolSA.cpp
Labels: bugfix

#3450 Object respawn functions
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaObjectDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaObjectDefs.h
  Client/mods/deathmatch/logic/rpc/CObjectRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CObjectRPCs.h
  Server/mods/deathmatch/logic/CObject.cpp
  Server/mods/deathmatch/logic/CObject.h
  Server/mods/deathmatch/logic/CPerfStat.RPCPacketUsage.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaObjectDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaObjectDefs.h
  Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp
  Shared/sdk/net/bitstream.h
  Shared/sdk/net/rpc_enums.h
Labels: enhancement

#3528 Add setVolumetricShadowsEnabled function
  Client/game_sa/CSettingsSA.cpp
  Client/game_sa/CSettingsSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.h
  Client/sdk/game/CSettings.h
Labels: enhancement

#3679 Add bone quaternion functions
  Client/game_sa/CEntitySA.cpp
  Client/game_sa/CEntitySA.h
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
  Client/sdk/game/CEntity.h
Labels: enhancement

#3590 Update CONTRIBUTING.md and links
  CONTRIBUTING.md
  README.md
Labels: documentation

#3717 Move CEF resources path
  Client/cefweb/CWebCore.cpp
  utils/buildactions/install_cef.lua
  vendor/cef3/premake5.lua
Labels: bugfix

#3713 Cleanup after 3679
  Client/game_sa/CEntitySA.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
Labels: refactor

#3754 Make objects respawnable by default
  Server/mods/deathmatch/logic/CObject.cpp
Labels: bugfix

#3720 Add new function isPlayerCrosshairVisible
  Client/game_sa/CHudSA.cpp
  Client/game_sa/CHudSA.h
  Client/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.h
  Client/sdk/game/CHud.h
Labels: enhancement
