Repository multitheftauto/mtasa-blue, pull requests merged in 2024-08, with the labels that each got.

#3594 Remove unnecessary argument in engineRestreamWorld
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/CClientIMG.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
Labels: refactor

#3625 Fix building crashes
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/mods/deathmatch/logic/CClientBuilding.cpp
  Client/sdk/game/CGame.h
Labels: bugfix

#3633 Fixed element health issues
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bugfix

#3606 Allow longer LOD distances
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
Labels: bugfix

#3611 Add model streaming functions
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientModel.cpp
  Client/mods/deathmatch/logic/CResource.cpp
  Client/mods/deathmatch/logic/CResource.h
  Client/mods/deathmatch/logic/CResourceModelStreamer.cpp
  Client/mods/deathmatch/logic/CResourceModelStreamer.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/lua/CLuaMain.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
  Client/sdk/game/CModelInfo.h
  Client/sdk/game/CStreaming.h
Labels: enhancement

#3567 Freeze Time functions
  Client/game_sa/CClockSA.cpp
  Client/game_sa/CClockSA.h
  Client/game_sa/CWeatherSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.h
  Client/sdk/game/CClock.h
Labels: bugfix

#3580 Optimization Handling (part 2)
  Client/game_sa/CHandlingEntrySA.cpp
  Client/game_sa/CHandlingEntrySA.h
  Client/game_sa/CHandlingManagerSA.cpp
  Client/game_sa/CHandlingManagerSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/sdk/game/CHandlingEntry.h
  Client/sdk/game/CHandlingManager.h
  Client/sdk/multiplayer/CMultiplayer.h
Labels: refactor

#3644 Fix Changing the "voiceptt" bind won't change it's "up" pressed state bind
  Client/core/CKeyBinds.cpp
Labels: enhancement

#3646 Add enginePreloadWorldArea function for preloading areas
  Client/game_sa/CStreamingSA.cpp
  Client/game_sa/CStreamingSA.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
  Client/sdk/game/CStreaming.h
Labels: enhancement

#3593 Make frame graph scale accordingly to resolution.
  Client/core/CChat.cpp
  Client/core/CChat.h
  Client/core/CGUI.cpp
  Client/core/CGUI.h
  Client/core/CGraphStats.cpp
Labels: enhancement

#3663 Fixes getTimerDetails negative remaining duration
  Shared/mods/deathmatch/logic/lua/CLuaTimer.cpp
Labels: bugfix

#3675 Fix engineRequestModel crash caused by CResourceModelStreamer
  Client/mods/deathmatch/logic/CResourceModelStreamer.cpp
Labels: bugfix

#3671 setElementModel memory leak fix
  Client/core/CCore.cpp
  Client/core/CCore.h
  Client/core/CModelCacheManager.cpp
  Client/core/CModelCacheManager.h
  Client/game_sa/CPedSA.cpp
  Client/game_sa/CPedSA.h
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/sdk/core/CCoreInterface.h
  Client/sdk/game/CPed.h
Labels: bugfix

#3614 Fix building OOP API
  Client/mods/deathmatch/logic/lua/CLuaMain.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaBuildingDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaBuildingDefs.h
Labels: bugfix

#3643 Deprecate setHelicopterRotorSpeed
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
Labels: enhancement

#3683 Adds new timer functions
  Client/mods/deathmatch/logic/lua/CLuaTimerManager.cpp
  Client/mods/deathmatch/logic/lua/CLuaTimerManager.h
  Client/mods/deathmatch/logic/luadefs/CLuaTimerDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaTimerDefs.h
  Server/mods/deathmatch/logic/lua/CLuaTimerManager.cpp
  Server/mods/deathmatch/logic/lua/CLuaTimerManager.h
  Server/mods/deathmatch/logic/luadefs/CLuaTimerDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaTimerDefs.h
  Shared/mods/deathmatch/logic/lua/CLuaTimer.cpp
  Shared/mods/deathmatch/logic/lua/CLuaTimer.h
Labels: enhancement
