Repository multitheftauto/mtasa-blue, pull requests merged in 2024-10, with the labels that each got.

#3753 Fix building crash
  Client/game_sa/CBuildingsPoolSA.cpp
  Client/game_sa/CEntitySA.h
Labels: bugfix

#3647 Fix Hydraulics stops working when using setVehicleHandling with player inside vehicle
  Client/game_sa/CVehicleSA.cpp
Labels: feedback, bugfix

#3592 Add new function spawnVehicleFlyingComponent
  Client/game_sa/CAutomobileSA.h
  Client/game_sa/CBikeSA.h
  Client/game_sa/CBmxSA.h
  Client/game_sa/CBoatSA.h
  Client/game_sa/CTrainSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Client/mods/deathmatch/logic/rpc/CVehicleRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CVehicleRPCs.h
  Client/sdk/game/CDamageManager.h
  Client/sdk/game/CVehicle.h
  Server/mods/deathmatch/logic/CPerfStat.RPCPacketUsage.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/CVehicle.h
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Shared/sdk/net/rpc_enums.h
Labels: enhancement

#3779 Fix #3770 Glob pattern in meta.xml should exclude meta.xml
  Server/mods/deathmatch/logic/CResource.cpp
Labels: bugfix

#2933 Fix #2932 (Fix CEF hardware acceleration not working)
  Client/cefweb/CWebApp.cpp
Labels: bug

#3596 Fix #523 Helicopter rotor unaffected by vehicle alpha
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: bugfix

#3796 Add "includeCustom" argument for getValidPedModels clientside
  Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Util.cpp
Labels: enhancement

#3684 Extract TXD pool class
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CPoolsSA.cpp
  Client/game_sa/CPoolsSA.h
  Client/game_sa/CTxdPoolSA.cpp
  Client/game_sa/CTxdPoolSA.h
  Client/mods/deathmatch/logic/CClientModel.cpp
  Client/mods/deathmatch/logic/CClientModelManager.cpp
  Client/sdk/game/CPools.h
  Client/sdk/game/CTxdPool.h
Labels: refactor
