Repository multitheftauto/mtasa-blue, pull requests merged in 2024-12, with the labels that each got.

#3837 Fix setVehicleDirtLevel
  Client/game_sa/CModelInfoSA.h
  Client/game_sa/gamesa_renderware.h
  Client/game_sa/gamesa_renderware.hpp
  Client/multiplayer_sa/CMultiplayerSA_Vehicles.cpp
Labels: enhancement, feedback, bugfix

#3879 Fix invalid target and owner references in projectiles
  Client/game_sa/CPlayerPedSA.cpp
  Client/game_sa/CProjectileInfoSA.cpp
  Client/game_sa/CProjectileInfoSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/sdk/game/CProjectileInfo.h
Labels: bugfix

#3880 Allow dynamic models to be created as buildings
  Client/game_sa/CBuildingsPoolSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientBuildingManager.cpp
  Client/sdk/game/CModelInfo.h
Labels: enhancement

#3886 Fix setServerConfigSetting crash
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bugfix

#3843 Refactor Quick Connect button
  Client/core/CClientVariables.cpp
  Client/core/CCommandFuncs.cpp
  Client/core/CConnectManager.cpp
  Client/core/CMainMenu.cpp
  Client/core/ServerBrowser/CServerBrowser.cpp
Labels: enhancement

#3808 add killPedTask function
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
  Client/sdk/game/CTaskManager.h
Labels: enhancement, feedback

#3904 dxDrawModel3D lighting
  Client/game_sa/CRendererSA.cpp
  Client/game_sa/CRendererSA.h
  Client/mods/deathmatch/logic/CModelRenderer.cpp
  Client/mods/deathmatch/logic/CModelRenderer.h
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.h
  Client/sdk/game/CRenderer.h
Labels: enhancement

#3706 Adding setVehicleNitroActivated server-side
  Client/mods/deathmatch/logic/rpc/CVehicleRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CVehicleRPCs.h
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Shared/sdk/net/rpc_enums.h
Labels: enhancement

#3704 Adding function addVehicleSirens & removeVehicleSirens client-side
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: enhancement

#3685 Make engineRestreamWorld more aggressive
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/game_sa/CPoolSAInterface.h
  Client/game_sa/CTxdPoolSA.cpp
  Client/game_sa/CTxdPoolSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/sdk/game/CGame.h
  Client/sdk/game/CModelInfo.h
  Client/sdk/game/CTxdPool.h
Labels: bugfix

#3667 Add setting to toggle photos taken by ingame camera to be saved in documents folder (fixes #3542)
  Client/core/CScreenShot.cpp
  Client/core/CScreenShot.h
  Client/core/CSettings.cpp
  Client/core/CSettings.h
Labels: enhancement

#3621 Fix #552 Impossible to stop helicopter rotor if it has a driver
  Client/game_sa/CHeliSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Client/sdk/game/CVehicle.h
Labels: bugfix

#3783 Add new functions setElementOnFire + isElementOnFire & deprecate setPedOnFire/isPedOnFire
  Client/game_sa/CEntitySA.h
  Client/game_sa/CObjectSA.cpp
  Client/game_sa/CObjectSA.h
  Client/game_sa/CPedSA.cpp
  Client/game_sa/CPedSA.h
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
  Client/mods/deathmatch/logic/CClientEntity.h
  Client/mods/deathmatch/logic/CClientObject.h
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CClientPed.h
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/CNetAPI.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
  Client/mods/deathmatch/logic/rpc/CElementRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CElementRPCs.h
  Client/sdk/game/CEntity.h
  Client/sdk/game/CObject.h
  Client/sdk/game/CPed.h
  Client/sdk/game/CVehicle.h
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CPed.h
  Server/mods/deathmatch/logic/CPerfStat.RPCPacketUsage.cpp
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/CVehicle.cpp
  Server/mods/deathmatch/logic/CVehicle.h
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
  Server/mods/deathmatch/logic/net/CSimVehiclePuresyncPacket.cpp
  Server/mods/deathmatch/logic/net/CSimVehiclePuresyncPacket.h
  Server/mods/deathmatch/logic/packets/CVehiclePuresyncPacket.cpp
  Shared/sdk/net/bitstream.h
  Shared/sdk/net/rpc_enums.h
Labels: enhancement

#3793 Add damageable objects support
  Client/game_sa/CModelInfoSA.cpp
  Client/game_sa/CModelInfoSA.h
  Client/mods/deathmatch/logic/CClientModel.cpp
  Client/mods/deathmatch/logic/CClientModel.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/sdk/game/CModelInfo.h
Labels: enhancement, bugfix

#3572 Add spawnFlyingComponent & breakGlass arguments for setVehiclePanelState
  Client/game_sa/CDamageManagerSA.cpp
  Client/game_sa/CDamageManagerSA.h
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/rpc/CVehicleRPCs.cpp
  Client/multiplayer_sa/CMultiplayerSA_Vehicles.cpp
  Client/sdk/game/CDamageManager.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Shared/sdk/net/bitstream.h
Labels: enhancement
