Repository multitheftauto/mtasa-blue, pull requests merged in 2024-05, with the labels that each got.

#3367 Fix file lock after img:destroy()
  Client/mods/deathmatch/logic/CClientIMG.cpp
  Client/mods/deathmatch/logic/CClientIMG.h
Labels: bugfix

#3203 Add meta.xml loading files pattern
  Server/mods/deathmatch/logic/CResource.cpp
  Server/mods/deathmatch/logic/CResource.h
  Server/mods/deathmatch/premake5.lua
  premake5.lua
  vendor/glob/LICENSE
  vendor/glob/include/glob/glob.h
  vendor/glob/premake5.lua
  vendor/glob/source/glob.cpp
Labels: enhancement

#3291 Trigger onClientPlayerWeaponSwitch Event for Remote Players (fix #1141)
  Client/mods/deathmatch/logic/rpc/CPlayerRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CPlayerRPCs.h
  Server/mods/deathmatch/logic/CRPCFunctions.cpp
  Shared/sdk/net/bitstream.h
  Shared/sdk/net/rpc_enums.h
Labels: bugfix

#3402 Render stages for 3D primitives
  Client/core/CCore.cpp
  Client/core/Graphics/CGraphics.cpp
  Client/core/Graphics/CGraphics.h
  Client/mods/deathmatch/logic/CClientColCircle.cpp
  Client/mods/deathmatch/logic/CClientColCuboid.cpp
  Client/mods/deathmatch/logic/CClientColPolygon.cpp
  Client/mods/deathmatch/logic/CClientColRectangle.cpp
  Client/mods/deathmatch/logic/CClientColTube.cpp
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
  Client/sdk/core/CGraphicsInterface.h
  Shared/sdk/CScriptArgReader.h
Labels: enhancement, bugfix

#3404 Add new functions to resource checker
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
Labels: bugfix

#3189 Add new functions: `pathListDir`, `pathIsFile`, `pathIsDirectory`
  Client/mods/deathmatch/logic/CResource.h
  Shared/mods/deathmatch/logic/lua/CLuaShared.cpp
  Shared/mods/deathmatch/logic/lua/CLuaShared.h
  Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaPathDefs.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaPathDefs.h
  Shared/sdk/SharedUtil.File.h
  Shared/sdk/SharedUtil.File.hpp
Labels: enhancement

#3371 Add LOD support for buildings
  Client/game_sa/CBuildingSA.cpp
  Client/game_sa/CBuildingSA.h
  Client/mods/deathmatch/logic/CClientBuilding.cpp
  Client/mods/deathmatch/logic/CClientBuilding.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.h
  Client/sdk/game/CBuilding.h
  Client/sdk/game/CWorld.h
Labels: enhancement

#3129 Fix #3037: Add ResetPedVoice function - Bug fix
  Client/game_sa/CPedSA.cpp
  Client/game_sa/CPedSA.h
  Client/mods/deathmatch/logic/CClientBuilding.h
  Client/mods/deathmatch/logic/CClientPed.h
Labels: bugfix

#3019 Add new account events: onAccountCreate/onAccountRemove
  Server/mods/deathmatch/logic/CAccount.cpp
  Server/mods/deathmatch/logic/CAccount.h
  Server/mods/deathmatch/logic/CAccountManager.cpp
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaAccountDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaAccountDefs.h
Labels: enhancement

#3384 Allow setElementCollisionsEnabled for buildings
  Client/mods/deathmatch/logic/CClientBuilding.cpp
  Client/mods/deathmatch/logic/CClientBuilding.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: enhancement

#3412 Fix render states spillover
  Client/core/CCore.cpp
  Client/core/Graphics/CGraphics.cpp
  Client/core/Graphics/CGraphics.h
Labels: bugfix
