Repository multitheftauto/mtasa-blue, pull requests merged in 2024-06, with the labels that each got.

#3413 Fix engineSetPoolCapacity crash
  Client/game_sa/CBuildingsPoolSA.cpp
  Client/game_sa/CBuildingsPoolSA.h
  Client/game_sa/CPedSA.cpp
  Client/game_sa/CPedSA.h
  Client/game_sa/CPoolsSA.h
  Client/sdk/game/CPools.h
Labels: bugfix

#3414 Fix SetBuildingPoolSize resets RemoveAllBuildings
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
Labels: bugfix

#3429 Add object specific contact radius and limit contact check
  Server/mods/deathmatch/logic/CMainConfig.cpp
  Server/mods/deathmatch/logic/packets/CPlayerPuresyncPacket.cpp
  Server/mods/deathmatch/mtaserver.conf
  Server/mods/deathmatch/mtaserver.conf.template
  Shared/mods/deathmatch/logic/CTickRateSettings.h
Labels: enhancement

#3461 Fix last contacted entity
  Client/game_sa/CBuildingsPoolSA.cpp
  Client/game_sa/CPedSA.h
Labels: bugfix

#3470 Fix createBuilding crash after engineSetPoolCapacity
  Client/game_sa/CBuildingsPoolSA.cpp
  Client/game_sa/CBuildingsPoolSA.h
  Client/game_sa/CPoolSAInterface.h
Labels: bugfix

#3477 Fix engineRestoreModelPhysicalPropertiesGroup restores incorrect group
  Client/game_sa/CModelInfoSA.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
Labels: backwards-incompatible, bugfix

#3469 Automatically resize building pool
  Client/mods/deathmatch/logic/CClientBuildingManager.cpp
  Client/mods/deathmatch/logic/CClientBuildingManager.h
  Client/mods/deathmatch/logic/luadefs/CLuaBuildingDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
Labels: bugfix

#3479 Cef compilation fix
  Client/cefweb/CWebView.cpp
  Client/cefweb/CWebView.h
Labels: bugfix

#3294 Fix small overhead in argument parser for strings
  Shared/mods/deathmatch/logic/lua/LuaBasic.cpp
Labels: bugfix

#3474 Fix outputDebugString level 4 colors
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Server/mods/deathmatch/logic/packets/CDebugEchoPacket.cpp
Labels: bugfix

#3480 Ped sync improvements
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CPedSync.cpp
  Server/mods/deathmatch/logic/CPedSync.cpp
  Server/mods/deathmatch/logic/packets/CPedSyncPacket.cpp
  Server/mods/deathmatch/logic/packets/CPedSyncPacket.h
  Shared/mods/deathmatch/logic/Utils.h
  Shared/sdk/CVector.h
  Shared/sdk/net/bitstream.h
Labels: enhancement

#3493 Generic exception type for argument parser instead of std::invalid_argument
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
Labels: enhancement

#3492 Fix onVehicleExit doesn't trigger if pulled out
  Server/mods/deathmatch/logic/CGame.cpp
Labels: bugfix

#3478 Postfx stage fix
  Client/core/CCore.cpp
  Client/core/CCore.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/sdk/core/CCoreInterface.h
  Client/sdk/multiplayer/CMultiplayer.h
Labels: bugfix

#3500 Update Windows Build instructions
  README.md
Labels: documentation

#3504 Implement getElementBoundingBox for buildings
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: enhancement

#3496 Fix #3495 OGG sound files can't be played as RAW data
  Client/mods/deathmatch/logic/CResourceManager.cpp
  Client/mods/deathmatch/logic/CResourceManager.h
  Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.cpp
  Shared/mods/deathmatch/logic/Utils.cpp
  Shared/mods/deathmatch/logic/Utils.h
Labels: bugfix

#3507 Fix #414 Using setElementHealth on a dead ped makes it invincible
  Client/mods/deathmatch/logic/CClientPed.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bugfix

#3490 Read a file directly from path - `fileRead` and `fileGetContents` update
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.h
  Shared/sdk/CChecksum.h
Labels: enhancement

#3494 Refactoring Part 3 - CLuaFunctionParser
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
Labels: refactor

#3499 Fix server-side debugscript behavior
  Server/mods/deathmatch/logic/CScriptDebugging.cpp
  Server/mods/deathmatch/logic/CScriptDebugging.h
Labels: bugfix

#3514 Appendum #3490
  Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp
Labels: bugfix

#3516 Update Rockstar copyright years.
  README.md
Labels: repo

#3510 Fix #501 Setting player model resets their current weapon slot
  Client/mods/deathmatch/logic/CClientPed.cpp
Labels: bugfix

#3522 Fix #512 setPedAnimation isn't synced properly on server side
  Server/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
Labels: bugfix

#3502 getPlayerScriptDebugLevel (Client)
  Client/mods/deathmatch/logic/CClientPlayer.h
  Client/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.h
  Client/mods/deathmatch/logic/rpc/CPlayerRPCs.cpp
  Client/mods/deathmatch/logic/rpc/CPlayerRPCs.h
  Server/mods/deathmatch/logic/CPerfStat.RPCPacketUsage.cpp
  Server/mods/deathmatch/logic/CPlayer.cpp
  Server/mods/deathmatch/logic/CPlayer.h
  Shared/sdk/net/rpc_enums.h
Labels: enhancement

#3487 Add Ability to Set Vehicle Wheel Rotation
  Client/game_sa/CVehicleSA.cpp
  Client/game_sa/CVehicleSA.h
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicle.h
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
  Client/sdk/game/CVehicle.h
Labels: enhancement

#3523 Fix #1860 Markers with type "arrow" or "checkpoint" won't be affected by alpha color argument
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: bugfix

#2989 Add new world properties (time cycle and weather related features)
  Client/game_sa/CWeatherSA.cpp
  Client/game_sa/CWeatherSA.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.h
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/sdk/game/CWeather.h
  Client/sdk/game/Common.h
  Client/sdk/multiplayer/CMultiplayer.h
Labels: enhancement

#3521 Fix setElementModel resets goggle effect
  Client/mods/deathmatch/logic/CClientPed.cpp
Labels: bugfix

#3517 Fix #452 Satchels get detached when skin is changed
  Client/game_sa/CPedSA.cpp
  Client/game_sa/CPedSA.h
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/sdk/game/CPed.h
Labels: bugfix

#3475 Fix Sirens not removed correctly
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bugfix

#3363 Global variable and default value for resource names
  Client/mods/deathmatch/logic/lua/CLuaMain.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaResourceDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaResourceDefs.h
  Server/mods/deathmatch/logic/lua/CLuaMain.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaResourceDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaResourceDefs.h
Labels: enhancement

#3491 Update DebugScript Cmd Syntax
  Server/mods/deathmatch/logic/CConsoleCommands.cpp
Labels: enhancement

#3524 Fix wrong function name for OOP debug level
  Client/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
Labels: bugfix
