Repository multitheftauto/mtasa-blue, pull requests merged in 2025-03, with the labels that each got.

#4021 Fix `sourceResourceRoot` for client-sided events
  Client/mods/deathmatch/logic/CMapEventManager.cpp
Labels: backwards-incompatible

#3511 Fix #539 Changing player position when he/she has a jetpack will remove the jetpack and bug when skin is changed
  Client/mods/deathmatch/logic/CClientPed.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: backwards-incompatible, bugfix

#4058 Fix CVehicleSA::BlowUp crash
  Client/game_sa/CVehicleSA.cpp
  Client/mods/deathmatch/logic/CClientVehicle.cpp
Labels: bugfix

#3656 CPedSA class cleanup & optimization
  Client/game_sa/CAEWeaponAudioEntitySA.h
  Client/game_sa/CPedSA.cpp
  Client/game_sa/CPedSA.h
  Client/game_sa/CPedSoundSA.cpp
  Client/game_sa/CPedSoundSA.h
  Client/game_sa/CWeaponSA.cpp
  Client/sdk/game/CPed.h
  Client/sdk/game/CWeaponInfo.h
Labels: refactor
