Repository multitheftauto/mtasa-blue, pull requests merged in 2025-09, with the labels that each got.

#4422 Fix cross-resource timer access (#827)
  Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Server/mods/deathmatch/logic/lua/CLuaManager.cpp
  Server/mods/deathmatch/logic/lua/CLuaManager.h
Labels: bugfix

#4385 Refactor framerate limiter to reduce CPU consumption
  Client/cefweb/CWebCore.cpp
  Client/cefweb/CWebCore.h
  Client/cefweb/CWebView.cpp
  Client/core/CClientVariables.cpp
  Client/core/CCommands.cpp
  Client/core/CCommands.h
  Client/core/CCore.cpp
  Client/core/CCore.h
  Client/core/CGraphStats.h
  Client/core/CMainMenu.cpp
  Client/core/CModManager.cpp
  Client/core/CSettings.cpp
  Client/core/CSettings.h
  Client/core/DXHook/CDirect3DEvents9.cpp
  Client/core/DXHook/CProxyDirect3D9.cpp
  Client/core/FPSLimiter.cpp
  Client/core/FPSLimiter.h
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Client/mods/deathmatch/logic/rpc/CWorldRPCs.cpp
  Client/sdk/core/CCoreInterface.h
  Client/sdk/core/CWebCoreInterface.h
  Client/sdk/core/FPSLimiterInterface.h
  Server/mods/deathmatch/logic/CMainConfig.cpp
  Server/mods/deathmatch/logic/CMainConfig.h
  Server/mods/deathmatch/logic/CMapManager.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Server/mods/deathmatch/logic/packets/CMapInfoPacket.cpp
  Server/mods/deathmatch/logic/packets/CMapInfoPacket.h
  Shared/sdk/Common.h
Labels: enhancement, refactor

#4467 Limit non-added event logging (#4466)
  Server/mods/deathmatch/logic/CGame.cpp
Labels: enhancement

#4357 Add functionality to re-stream models separately
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientGame.h
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
  Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
  Client/sdk/core/CClientBase.h
  Client/sdk/game/CStreaming.h
Labels: enhancement

#4492 The second iteration of element data optimization
  Client/mods/deathmatch/logic/CClientEntity.cpp
  Client/mods/deathmatch/logic/CClientEntity.h
  Client/mods/deathmatch/logic/CCustomData.cpp
  Client/mods/deathmatch/logic/CCustomData.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/lua/CLuaArgument.cpp
  Client/mods/deathmatch/logic/lua/CLuaArgument.h
  Client/mods/deathmatch/logic/lua/CLuaArguments.cpp
  Client/mods/deathmatch/logic/lua/CLuaArguments.h
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Client/mods/deathmatch/logic/rpc/CElementRPCs.cpp
  Server/mods/deathmatch/logic/CCustomData.cpp
  Server/mods/deathmatch/logic/CCustomData.h
  Server/mods/deathmatch/logic/CElement.cpp
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CPlayer.cpp
  Server/mods/deathmatch/logic/CPlayer.h
  Server/mods/deathmatch/logic/CPlayerManager.cpp
  Server/mods/deathmatch/logic/CPlayerManager.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Server/mods/deathmatch/logic/lua/CLuaArgument.cpp
  Server/mods/deathmatch/logic/lua/CLuaArgument.h
  Server/mods/deathmatch/logic/lua/CLuaArguments.cpp
  Server/mods/deathmatch/logic/lua/CLuaArguments.h
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp
  Shared/mods/deathmatch/logic/luadefs/CLuaElementDefsShared.cpp
Labels: enhancement
