Repository multitheftauto/mtasa-blue, pull requests merged in 2025-01, with the labels that each got.

#3761 Add new mtaserver.conf rules for server browser/list
  Server/mods/deathmatch/editor.conf
  Server/mods/deathmatch/local.conf
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CMainConfig.cpp
  Server/mods/deathmatch/logic/CMainConfig.h
  Server/mods/deathmatch/mtaserver.conf
  Server/mods/deathmatch/mtaserver.conf.template
Labels: enhancement

#3520 Fix #467 Ped animations don't sync for new players
  Client/mods/deathmatch/logic/CClientPed.h
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Client/mods/deathmatch/logic/CPedSync.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Server/mods/deathmatch/logic/CPed.h
  Server/mods/deathmatch/logic/CPedSync.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp
  Shared/sdk/net/bitstream.h
Labels: bugfix

#3946 Server side getColPolygonHeight fix
  Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
Labels: backwards-incompatible, bugfix

#3597 Add "flyingcomponents" special world property
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/mods/deathmatch/logic/CClientVehicle.cpp
  Client/mods/deathmatch/logic/CClientVehicleManager.h
  Client/mods/deathmatch/logic/CNetAPI.cpp
  Client/mods/deathmatch/logic/CPacketHandler.cpp
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/packets/CMapInfoPacket.cpp
  Shared/mods/deathmatch/logic/Enums.cpp
  Shared/mods/deathmatch/logic/Enums.h
  Shared/sdk/net/SyncStructures.h
  Shared/sdk/net/bitstream.h
Labels: enhancement

#3627 Add removeGameWorld and restoreGameWorld
  Client/game_sa/CBuildingsPoolSA.cpp
  Client/game_sa/CBuildingsPoolSA.h
  Client/game_sa/CDummyPoolSA.cpp
  Client/game_sa/CDummyPoolSA.h
  Client/game_sa/CEntitySA.h
  Client/game_sa/CGameSA.cpp
  Client/game_sa/CGameSA.h
  Client/game_sa/CPoolSAInterface.h
  Client/game_sa/CPoolsSA.h
  Client/mods/deathmatch/logic/CClientBuildingManager.cpp
  Client/mods/deathmatch/logic/CClientBuildingManager.h
  Client/mods/deathmatch/logic/luadefs/CLuaBuildingDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaWorldDefs.h
  Client/sdk/game/CBuildingsPool.h
  Client/sdk/game/CDummyPool.h
  Client/sdk/game/CGame.h
  Client/sdk/game/CWorld.h
  Server/mods/deathmatch/logic/CResourceChecker.Data.h
Labels: enhancement, bugfix

#3537 Refactor server CLuaBlipDefs to use new parser
  Server/mods/deathmatch/logic/CBlip.h
  Server/mods/deathmatch/logic/luadefs/CLuaBlipDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaBlipDefs.h
Labels: refactor

#3536 Refactor client CLuaBlipDefs to use new parser
  Client/mods/deathmatch/logic/CClientRadarMarker.h
  Client/mods/deathmatch/logic/CClientRadarMarkerManager.h
  Client/mods/deathmatch/logic/luadefs/CLuaBlipDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaBlipDefs.h
Labels: refactor

#3944 Refactor CLuaTeamDefs (client)
  Client/mods/deathmatch/logic/CClientTeam.cpp
  Client/mods/deathmatch/logic/CClientTeam.h
  Client/mods/deathmatch/logic/luadefs/CLuaTeamDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaTeamDefs.h
Labels: refactor

#3945 Refactor CLuaTeamDefs (server)
  Server/mods/deathmatch/logic/CTeam.cpp
  Server/mods/deathmatch/logic/CTeam.h
  Server/mods/deathmatch/logic/luadefs/CLuaTeamDefs.cpp
  Server/mods/deathmatch/logic/luadefs/CLuaTeamDefs.h
Labels: refactor

#3969 Fix restoreGameWorld and removeWorldModel conflict
  Client/game_sa/CBuildingsPoolSA.cpp
Labels: bugfix

#3973 Apply element filter for buildings in engineApplyShaderToWorldTexture
  Client/game_sa/CBuildingsPoolSA.cpp
  Client/game_sa/CBuildingsPoolSA.h
  Client/game_sa/CPoolsSA.cpp
  Client/mods/deathmatch/logic/CClientGame.cpp
  Client/multiplayer_sa/multiplayersa_init.cpp
Labels: enhancement

#3981 Fix SVG bitmap and optimize rendering
  Client/mods/deathmatch/logic/CClientVectorGraphicDisplay.cpp
  Client/mods/deathmatch/logic/CClientVectorGraphicDisplay.h
Labels: bugfix

#3964 Fix unintended behavior for ped control states
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
  Client/mods/deathmatch/logic/luadefs/CLuaCompatibilityDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
Labels: refactor

#3941 Add new event onPlayerTeleport.
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CMainConfig.cpp
  Server/mods/deathmatch/logic/CPlayer.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Server/mods/deathmatch/logic/packets/CPlayerPuresyncPacket.cpp
  Server/mods/deathmatch/mtaserver.conf
  Server/mods/deathmatch/mtaserver.conf.template
  Shared/mods/deathmatch/logic/CTickRateSettings.h
Labels: enhancement

#3987 Ped's camera synchronization
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CClientPed.h
  Client/mods/deathmatch/logic/CPedSync.cpp
  Server/mods/deathmatch/logic/CPed.h
  Server/mods/deathmatch/logic/CPedSync.cpp
  Server/mods/deathmatch/logic/packets/CPedStartSyncPacket.cpp
  Server/mods/deathmatch/logic/packets/CPedSyncPacket.cpp
  Server/mods/deathmatch/logic/packets/CPedSyncPacket.h
  Shared/sdk/SharedUtil.Math.h
  Shared/sdk/net/bitstream.h
Labels: enhancement, bugfix

#3988 Add download progress handler for CEF in premake
  utils/buildactions/install_cef.lua
  utils/buildactions/utils.lua
Labels: enhancement

#3989 Fix jetpack crash
  Client/game_sa/CBuildingsPoolSA.cpp
Labels: bugfix

#3990 Fix false positive in `onPlayerTeleport` event when using `spawnPlayer`
  Server/mods/deathmatch/logic/CMapManager.cpp
  Server/mods/deathmatch/logic/packets/CPlayerPuresyncPacket.cpp
Labels: bugfix
