Repository multitheftauto/mtasa-blue, pull requests merged in 2025-10, with the labels that each got.

#4504 `getElementDistanceFromCentreOfMassToBaseOfModel` add 'building'
  Client/mods/deathmatch/logic/CClientBuilding.cpp
  Client/mods/deathmatch/logic/CClientBuilding.h
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: enhancement

#4503 Cancel data change
  Server/mods/deathmatch/logic/CElement.cpp
  Server/mods/deathmatch/logic/CElement.h
  Server/mods/deathmatch/logic/CGame.cpp
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: enhancement

#4502 Fix getElementsWithinRange not working in client-side with building
  Client/mods/deathmatch/logic/CClientBuilding.cpp
Labels: enhancement

#4431 Fix remote player fist/melee strafing sync
  Client/game_sa/CPedIntelligenceSA.cpp
  Client/game_sa/CPedIntelligenceSA.h
  Client/multiplayer_sa/multiplayer_keysync.cpp
  Client/sdk/game/CPedIntelligence.h
Labels: sync, bugfix

#4440 Fixes (#4036) - Preserve user key bindings when unbinding resource keys
  Client/core/CKeyBinds.cpp
  Client/core/CKeyBinds.h
  Client/mods/deathmatch/logic/CResource.cpp
  Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
  Client/mods/deathmatch/logic/rpc/CInputRPCs.cpp
  Client/sdk/core/CKeyBindsInterface.h
  Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
Labels: bugfix

#4398 Fix vehicle upgrades (engineRequestModel)
  Client/mods/deathmatch/logic/CVehicleUpgrades.cpp
Labels: bugfix

#4401 Fix missing swimming animation
  Client/game_sa/CPedSA.cpp
  Client/game_sa/CPedSA.h
  Client/game_sa/CTaskManagementSystemSA.cpp
  Client/game_sa/CTasksSA.cpp
  Client/game_sa/CTasksSA.h
  Client/game_sa/TaskBasicSA.cpp
  Client/game_sa/TaskBasicSA.h
  Client/game_sa/TaskSimpleSwimSA.cpp
  Client/game_sa/TaskSimpleSwimSA.h
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CClientPed.h
  Client/mods/deathmatch/logic/CNetAPI.cpp
  Client/sdk/game/CPed.h
  Client/sdk/game/CTasks.h
  Client/sdk/game/TaskBasic.h
  Client/sdk/game/TaskSimpleSwim.h
  Shared/sdk/enums/SurfaceType.h
Labels: sync, bugfix
