Repository multitheftauto/mtasa-blue, pull requests merged in 2025-05, with the labels that each got.

#4169 Add StringName
  Client/mods/deathmatch/StdInc.h
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Server/mods/deathmatch/StdInc.h
  Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
  Shared/mods/deathmatch/logic/CStringName.cpp
  Shared/mods/deathmatch/logic/CStringName.h
  Shared/mods/deathmatch/logic/luadefs/CLuaElementDefsShared.cpp
  Shared/sdk/CIntrusiveDoubleLinkedList.h
  Shared/sdk/CScriptArgReader.h
  vendor/lua/src/lapi.c
  vendor/lua/src/lstring.c
  vendor/lua/src/lstring.h
  vendor/lua/src/lua.h
Labels: enhancement

#4196 Fix setPedOnFire(ped, false) doesn't cancel TASK_SIMPLE_PLAYER_ON_FIRE (again and again)
  Client/game_sa/CFireSA.cpp
  Client/game_sa/CFireSA.h
  Client/game_sa/CGameSA.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
Labels: bugfix

#4195 Fix ignorefirestate behaviour
  Client/multiplayer_sa/CMultiplayerSA.cpp
  Client/multiplayer_sa/CMultiplayerSA.h
  Client/multiplayer_sa/CMultiplayerSA_Tasks.cpp
Labels: bugfix

#4206 Potential crash fix
  Client/multiplayer_sa/CMultiplayerSA.cpp
Labels: bugfix

#4207 Client freezes fix
  Client/game_sa/CWeatherSA.cpp
Labels: bugfix

#4218 Potential fix for #4209
  vendor/lua/src/lstring.c
Labels: bugfix

#4201 Streaming fix
  Client/mods/deathmatch/logic/CClientObject.cpp
  Client/mods/deathmatch/logic/CClientPed.cpp
  Client/mods/deathmatch/logic/CClientStreamElement.h
  Client/mods/deathmatch/logic/CClientStreamer.h
  Client/mods/deathmatch/logic/CClientVehicle.cpp
Labels: bugfix

#4224 Allow using std::variant with several pointers (Lua parser)
  Shared/mods/deathmatch/logic/lua/CLuaFunctionParser.h
Labels: enhancement

#4186 Allow fx parameters for a player's voice
  Client/mods/deathmatch/logic/CClientPlayerVoice.cpp
  Client/mods/deathmatch/logic/CClientPlayerVoice.h
  Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.cpp
Labels: enhancement

#4203 Fix bone related functions
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
  Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.h
Labels: enhancement, refactor
